const KEY='klassencloud-v5';let currentUser=null,view='dashboard',chatMode='class',selectedClass=null,selectedUser=null,selectedGroup=null,state={theme:'dark',files:[],events:[]};
const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
async function api(u,o={}){const r=await fetch(u,{headers:{'Content-Type':'application/json',...(o.headers||{})},...o});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(d.error||'Fehler');return d}
function toast(x){const e=document.createElement('div');e.className='toast';e.textContent=x;$('#toasts').append(e);setTimeout(()=>e.remove(),2400)}
function initials(n){return n.split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase()}
async function boot(){if(location.protocol==='file:'){showAuth();const e=$('#loginError');e.textContent='Bitte öffne KlassenCloud über den gestarteten Server. Die Anmeldung benötigt die laufende App-API.';return}try{const d=await api('/api/me');currentUser=d.user;enter()}catch{showAuth()}}
function showAuth(){$('#authScreen').classList.remove('hidden')}
function enter(){$('#authScreen').classList.add('hidden');$('#adminNav').hidden=currentUser.role!=='admin';render()}
function setView(v){view=v;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===v));$('#breadcrumbs').textContent={dashboard:'Dashboard',chat:'Chats',cloud:'Cloud',groups:'Gruppen',calendar:'Termine',timetable:'Stundenplan',profile:'Profil',admin:'Administration'}[v]||v;render()}
function render(){document.body.classList.toggle('light',state.theme==='light');let a=$('#app');if(view==='dashboard')a.innerHTML=dashboard();if(view==='chat')chatView();if(view==='cloud')a.innerHTML=cloud();if(view==='groups')a.innerHTML=groups();if(view==='calendar')a.innerHTML=calendar();if(view==='timetable')a.innerHTML=timetable();if(view==='profile')a.innerHTML=profile();if(view==='admin')adminView();bind()}
function dashboard(){return `<div class="hero"><div><span class="muted">Guten Abend 👋</span><h1>Willkommen, ${esc(currentUser.name)}</h1><p>Deine KlassenCloud – Chats, Klassen, Cloud, Kalender und Stundenplan an einem Ort.</p></div><div class="hero-art">☁️</div></div><div class="dashboard-row-scroll"><div class="card stat"><span>💬</span><div><b>Chats</b><small>privat & Klasse</small></div></div><div class="card stat"><span>🛡</span><div><b>${currentUser.role==='admin'?'Admin':'Mitglied'}</b><small>deine Berechtigung</small></div></div><div class="card stat"><span>🔒</span><div><b>Privat</b><small>nur Beteiligte</small></div></div><div class="card stat"><span>👥</span><div><b>Geschützt</b><small>Klassenräume</small></div></div></div><div class="two-col"><div class="card"><h2>🚀 Schnellzugriff</h2><p class="muted">Auf dem Handy kannst du die Navigation über ☰ ein- und ausblenden. Auf PC und Tablet kannst du sie mit „Dashboard“ einklappen.</p><div class="list"><button class="secondary" data-go="chat">💬 Zu den Chats</button><button class="secondary" data-go="calendar">📅 Kalender öffnen</button><button class="secondary" data-go="timetable">🕐 Stundenplan öffnen</button></div></div><div class="card"><h2>🔐 Datenschutz</h2><p class="muted">Private Chats und geschützte Klassenbereiche bleiben nur für berechtigte Mitglieder sichtbar.</p></div></div>`}
async function chatView(){
 const a=$('#app');a.innerHTML='<div class="loading">Chats werden geladen …</div>';
 try{
  const o=await api('/api/chat/overview'),users=await api('/api/chat/users'),groups=await api('/api/groups');
  a.innerHTML=`<div class="chat-layout"><div class="card chat-list scroll-frame y">
   <div class="section-head"><h2>Chats</h2><button class="secondary" id="newGroup">＋ Gruppe</button></div>
   <div class="chat-section"><b>🏫 Klassen</b>${o.classes.length?o.classes.map(c=>`<button class="chat-contact ${chatMode==='class'&&selectedClass===c.id?'active':''}" data-class="${c.id}"><div class="mini-avatar">👥</div><div><b>${esc(c.name)}</b><div class="muted">${c.memberCount} Mitglieder · geschützt</div></div></button>`).join(''):'<div class="muted pad">Keine Klasse freigeschaltet.</div>'}</div>
   <div class="chat-section"><b>👥 Meine Gruppen</b>${groups.groups.length?groups.groups.map(g=>`<button class="chat-contact ${chatMode==='group'&&selectedGroup===g.id?'active':''}" data-group="${g.id}"><div class="mini-avatar">${initials(g.name)}</div><div><b>${esc(g.name)}</b><div class="muted">${g.memberCount} Mitglieder · ${g.closed?'🔒 geschlossen':'offen'}</div></div></button>`).join(''):'<div class="muted pad">Noch keine Gruppen.</div>'}</div>
   <div class="chat-section"><b>🔒 Private Chats</b>${o.privateChats.map(c=>`<button class="chat-contact ${chatMode==='private'&&selectedUser===c.other.id?'active':''}" data-user="${c.other.id}"><div class="mini-avatar">${initials(c.other.name)}</div><div><b>${esc(c.other.name)}</b><div class="status ${c.other.online?'online':'offline'}">${c.other.online?'● Online':'○ Offline'}</div></div></button>`).join('')}<button class="secondary full" id="newPrivate">＋ Privaten Chat starten</button></div>
  </div><div class="card chat-window" id="chatWindow"><div class="muted" style="margin:auto">Wähle links einen Chat.</div></div></div>`;
  window.chatUsers=users.users;window.chatGroups=groups.groups;bind();
 }catch(e){a.innerHTML=`<div class="card">${esc(e.message)}</div>`}
}
async function openClass(id){chatMode='class';selectedClass=id;await drawChat(`/api/chat/class/${id}`,'class',id)}
async function openPrivate(id){chatMode='private';selectedUser=id;await drawChat(`/api/chat/private/${id}`,'private',id)}
async function openGroup(id){chatMode='group';selectedGroup=id;await drawGroup(id)}
function stopChatPoll(){if(window._chatPoll)clearInterval(window._chatPoll);if(window._typingPoll)clearInterval(window._typingPoll);window._chatPoll=null;window._typingPoll=null}
function messageHtml(m,canDelete=true){return `<div class="bubble ${m.userId===currentUser.id?'me':''}" data-message="${m.id}"><div><b>${esc(m.userName)}</b>${m.userId===currentUser.id?' <span class="muted">(du)</span>':''}</div><div>${esc(m.text)}</div><small>${new Date(m.createdAt).toLocaleString('de-DE')} ${canDelete&& (m.userId===currentUser.id||currentUser.role==='admin')?`<button class="msg-delete" data-msg-delete="${m.id}" title="Nachricht löschen">🗑</button>`:''}</small></div>`}
function bindMessageActions(){document.querySelectorAll('[data-msg-delete]').forEach(b=>b.onclick=async()=>{try{await api('/api/messages/'+b.dataset.msgDelete,{method:'DELETE'});toast('Nachricht gelöscht');if(chatMode==='group')drawGroup(selectedGroup);else drawChat(chatMode==='class'?`/api/chat/class/${selectedClass}`:`/api/chat/private/${selectedUser}`,chatMode,chatMode==='class'?selectedClass:selectedUser)}catch(e){toast(e.message)}})}
async function drawChat(endpoint,type,id){
 stopChatPoll();const w=$('#chatWindow');w.innerHTML='<div class="loading">Chat wird geladen …</div>';
 try{
  const d=await api(endpoint), title=type==='class'?d.class.name:d.chat.other.name, sub=type==='class'?'Geschützter Klassenchat – nur Mitglieder':`Privater Chat · ${d.chat.other.online?'● Online':'○ Offline'}`;
  w.innerHTML=`<div class="chat-head"><div class="mini-avatar">${type==='class'?'👥':initials(title)}</div><div class="grow"><b>${esc(title)}</b><div class="muted" id="chatStatus">${esc(sub)}</div></div><button class="secondary" id="searchChat">🔎 Suchen</button></div>
   <div class="messages scroll-frame y" id="messages">${d.messages.length?d.messages.map(messageHtml).join(''):'<div class="muted" style="margin:auto">Noch keine Nachrichten.</div>'}<div id="typingIndicator" class="typing-indicator"></div></div>
   <form class="chat-form" id="chatForm"><input class="input" name="text" maxlength="2000" autocomplete="off" placeholder="Nachricht schreiben …" required><button class="primary">Senden</button></form>
   <div id="chatSearchBox" class="chat-search hidden"><input class="input" id="chatSearchInput" placeholder="Chat durchsuchen …"><div id="chatSearchResults"></div></div>`;
  const msgs=$('#messages');msgs.scrollTop=msgs.scrollHeight;bindMessageActions();
  $('#chatForm').onsubmit=async e=>{e.preventDefault();const input=e.target.text,text=input.value.trim();if(!text)return;try{await api(endpoint,{method:'POST',body:JSON.stringify({text})});input.value='';await drawChat(endpoint,type,id)}catch(x){toast(x.message)}};
  const input=$('#chatForm input[name=text]');input.oninput=()=>api(`/api/typing/${type}/${id}`,{method:'POST',body:JSON.stringify({typing:!!input.value.trim()})}).catch(()=>{});
  $('#searchChat').onclick=()=>{$('#chatSearchBox').classList.toggle('hidden');if(!$('#chatSearchBox').classList.contains('hidden'))$('#chatSearchInput').focus()};
  $('#chatSearchInput').oninput=async e=>{const q=e.target.value.trim(),r=$('#chatSearchResults');if(q.length<2){r.innerHTML='';return}try{const x=await api(`/api/chat/search/${type}/${id}?q=${encodeURIComponent(q)}`);r.innerHTML=x.messages.length?x.messages.map(m=>`<div class="search-hit"><b>${esc(m.userName)}</b> · ${new Date(m.createdAt).toLocaleString('de-DE')}<br>${esc(m.text)}</div>`).join(''):'<div class="muted">Keine Treffer.</div>'}catch(x){r.innerHTML=`<div class="auth-error">${esc(x.message)}</div>`}};
  window._chatPoll=setInterval(async()=>{try{const x=await api(endpoint);const old=msgs.scrollHeight-msgs.scrollTop-msgs.clientHeight;msgs.innerHTML=x.messages.length?x.messages.map(messageHtml).join(''):'<div class="muted" style="margin:auto">Noch keine Nachrichten.</div>';if(old<80)msgs.scrollTop=msgs.scrollHeight;bindMessageActions();const t=x.typing||[];$('#typingIndicator').textContent=t.length?t.map(u=>u.name).join(', ')+' schreibt gerade …':''}catch{}},1800);
  window._typingPoll=setInterval(async()=>{try{const x=await api(`/api/typing/${type}/${id}`);const t=x.users||[];$('#typingIndicator').textContent=t.length?t.map(u=>u.name).join(', ')+' schreibt gerade …':''}catch{}},1000);
 }catch(e){w.innerHTML=`<div class="card">${esc(e.message)}</div>`}
}
async function drawGroup(id){
 stopChatPoll();const w=$('#chatWindow');w.innerHTML='<div class="loading">Gruppe wird geladen …</div>';
 try{
  const d=await api('/api/groups/'+id),isOwner=d.group.ownerId===currentUser.id||currentUser.role==='admin';
  const files=d.files||[],events=d.events||[];
  w.innerHTML=`<div class="chat-head"><div class="mini-avatar">${initials(d.group.name)}</div><div class="grow"><b>${esc(d.group.name)}</b><div class="muted">${d.members.length} Mitglieder · Besitzer: ${esc(d.group.ownerName)} · ${d.group.closed?'🔒 geschlossen':'🟢 offen'}</div></div>${isOwner?`<button class="secondary" id="manageGroup">Mitglieder</button><button class="secondary" id="toggleGroup">${d.group.closed?'🔓 Öffnen':'🔒 Schließen'}</button><button class="danger" id="deleteGroup">Löschen</button>`:''}</div>
  <div class="group-tabs"><button class="secondary active" data-gtab="chat">💬 Chat</button><button class="secondary" data-gtab="files">📎 Dateien</button><button class="secondary" data-gtab="events">📅 Termine</button></div>
  <div id="groupBody"></div>`;
  const renderTab=async tab=>{
   const body=$('#groupBody');
   if(tab==='chat'){body.innerHTML=`<div class="group-chat-tools"><button class="secondary" id="groupSearch">🔎 Chat durchsuchen</button></div><div class="messages scroll-frame y" id="messages">${d.messages.length?d.messages.map(messageHtml).join(''):'<div class="muted" style="margin:auto">Noch keine Nachrichten.</div>'}<div id="typingIndicator" class="typing-indicator"></div></div>${d.group.closed&&!isOwner&&currentUser.role!=='admin'?'<div class="closed-note">🔒 Diese Gruppe ist geschlossen. Nur der Verlauf kann noch gelesen werden.</div>':`<form class="chat-form" id="groupForm"><input class="input" name="text" maxlength="2000" placeholder="In die Gruppe schreiben …" required><button class="primary">Senden</button></form>`}`;const msgs=$('#messages');if(msgs){msgs.scrollTop=msgs.scrollHeight;bindMessageActions()}const gs=$('#groupSearch');if(gs)gs.onclick=()=>{const q=prompt('Suchbegriff im Gruppenchat:');if(!q||q.trim().length<2)return;api(`/api/chat/search/group/${id}?q=${encodeURIComponent(q.trim())}`).then(x=>toast(`${x.messages.length} Treffer gefunden`)).catch(e=>toast(e.message))};const gf=$('#groupForm');if(gf)gf.onsubmit=async e=>{e.preventDefault();try{await api('/api/groups/'+id,{method:'POST',body:JSON.stringify({text:new FormData(e.target).get('text')})});await drawGroup(id)}catch(x){toast(x.message)}};const inp=$('#groupForm input');if(inp)inp.oninput=()=>api(`/api/typing/group/${id}`,{method:'POST',body:JSON.stringify({typing:!!inp.value.trim()})}).catch(()=>{});
   if(!d.group.closed){window._typingPoll=setInterval(async()=>{try{const x=await api(`/api/typing/group/${id}`);$('#typingIndicator').textContent=(x.users||[]).map(u=>u.name).join(', ')+(x.users?.length?' schreibt gerade …':'')}catch{}},1000)}
  } else if(tab==='files'){body.innerHTML=`<div class="section-head"><div><h3>📎 Gemeinsame Dateien</h3><span class="muted">Nur Gruppenmitglieder können diese Dateien sehen.</span></div><button class="primary" id="groupUpload">＋ Datei teilen</button></div><div class="scroll-frame both cloud-scroll"><div class="file-grid">${files.length?files.map(f=>`<div class="file-card"><div class="file-icon">📄</div><h3>${esc(f.name)}</h3><div class="muted">${formatBytes(f.size)} · von ${esc(f.ownerName)}</div><div class="file-actions"><button class="secondary" data-gfile="${f.id}">⬇ Herunterladen</button></div></div>`).join(''):'<div class="muted">Noch keine gemeinsamen Dateien.</div>'}</div></div>`;$('#groupUpload').onclick=()=>groupUpload(id);document.querySelectorAll('[data-gfile]').forEach(b=>b.onclick=async()=>{try{const d=await api(`/api/groups/${id}/files/${b.dataset.gfile}/download`);window.location=d.url}catch(e){toast(e.message)}});
  } else {body.innerHTML=`<div class="section-head"><div><h3>📅 Gemeinsame Termine</h3><span class="muted">Termine nur für diese Gruppe.</span></div><button class="primary" id="groupEvent">＋ Termin</button></div><div class="scroll-frame y page-scroll"><div class="list">${events.length?events.map(e=>`<div class="list-row"><div class="stat-icon">📅</div><div class="grow"><b>${esc(e.title)}</b><div class="muted">${e.date} · ${e.time}</div>${e.description?`<div class="muted">${esc(e.description)}</div>`:''}<small class="muted">von ${esc(e.creatorName)}</small></div>${isOwner||e.creatorId===currentUser.id?`<button class="danger" data-gevent="${e.id}">Löschen</button>`:''}</div>`).join(''):'<div class="muted">Noch keine Termine.</div>'}</div></div>`;$('#groupEvent').onclick=()=>groupEventDialog(id);document.querySelectorAll('[data-gevent]').forEach(b=>b.onclick=async()=>{if(confirm('Termin löschen?')){await api(`/api/groups/${id}/events/${b.dataset.gevent}`,{method:'DELETE'});drawGroup(id)}})}
  };
  document.querySelectorAll('[data-gtab]').forEach(b=>b.onclick=()=>{stopChatPoll();document.querySelectorAll('[data-gtab]').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderTab(b.dataset.gtab)});
  renderTab('chat');
  const mg=$('#manageGroup');if(mg)mg.onclick=()=>manageGroup(d);
  const tg=$('#toggleGroup');if(tg)tg.onclick=async()=>{try{await api('/api/groups/'+id+'/status',{method:'PATCH',body:JSON.stringify({closed:!d.group.closed})});drawGroup(id);toast(d.group.closed?'Gruppe geöffnet':'Gruppe geschlossen')}catch(e){toast(e.message)}};
  const dg=$('#deleteGroup');if(dg)dg.onclick=async()=>{if(confirm('Gruppe wirklich löschen?')){await api('/api/groups/'+id,{method:'DELETE'});selectedGroup=null;chatView();toast('Gruppe gelöscht')}};
 }catch(e){w.innerHTML=`<div class="card">${esc(e.message)}</div>`}
}
async function groups(){const a=$('#app');a.innerHTML='<div class="loading">Gruppen werden geladen …</div>';try{const d=await api('/api/groups');a.innerHTML=`<div class="section-head"><div><h2>👥 Meine Gruppen</h2><div class="muted">Nur Gruppenmitglieder sehen private Gruppen. Besitzer können Gruppen schließen und Mitglieder verwalten.</div></div><button class="primary" id="groupsNew">＋ Gruppe erstellen</button></div><div class="scroll-frame both groups-scroll"><div class="group-grid">${d.groups.length?d.groups.map(g=>`<div class="card group-card"><div class="mini-avatar">${initials(g.name)}</div><h3>${esc(g.name)}</h3><div class="muted">${g.memberCount} Mitglieder · Besitzer: ${esc(g.ownerName)}</div><div class="members">${(g.members||[]).slice(0,6).map(m=>`<div class="mini-avatar" title="${esc(m.name)}">${initials(m.name)}</div>`).join('')}</div><div class="muted">${g.closed?'🔒 Geschlossen':'🟢 Offen'}</div><button class="secondary full" data-open-group="${g.id}">💬 Gruppe öffnen</button></div>`).join(''):'<div class="card"><div class="muted">Du bist noch in keiner Gruppe.</div></div>'}</div></div>`;document.querySelectorAll('[data-open-group]').forEach(b=>b.onclick=()=>{selectedGroup=Number(b.dataset.openGroup);chatMode='group';setView('chat');setTimeout(()=>openGroup(selectedGroup),0)});$('#groupsNew').onclick=async()=>{const name=prompt('Name der neuen Gruppe:');if(!name?.trim())return;const users=(await api('/api/groups/users')).users;const selected=prompt('Mitglieder hinzufügen (Namen mit Komma trennen):\n\n'+users.map(u=>u.name).join('\n'));const names=(selected||'').split(',').map(x=>x.trim().toLowerCase()).filter(Boolean);const ids=users.filter(u=>names.includes(u.name.toLowerCase())).map(u=>u.id);try{await api('/api/groups',{method:'POST',body:JSON.stringify({name:name.trim(),memberIds:ids})});groups();toast('Gruppe erstellt')}catch(e){toast(e.message)}}}catch(e){a.innerHTML=`<div class="card">${esc(e.message)}</div>`}}
async function groupUpload(id){const d=document.createElement('dialog');d.className='dialog';d.innerHTML=`<form class="dialog-card"><div class="dialog-head"><h3>Datei für die Gruppe</h3><button type="button" class="icon-btn" id="x">×</button></div><input class="input" type="file" id="gf" required><button class="primary">Hochladen</button><div id="ge" class="auth-error"></div></form>`;document.body.append(d);d.showModal();$('#x').onclick=()=>d.remove();d.querySelector('form').onsubmit=async e=>{e.preventDefault();const f=$('#gf').files[0];if(!f)return;const r=new FileReader();r.onload=async()=>{try{await api(`/api/groups/${id}/files`,{method:'POST',body:JSON.stringify({name:f.name,mime:f.type,data:r.result})});d.close();d.remove();drawGroup(id);toast('Datei geteilt')}catch(x){$('#ge').textContent=x.message}};r.readAsDataURL(f)}}
function groupEventDialog(id){const d=document.createElement('dialog');d.className='dialog';d.innerHTML=`<form class="dialog-card"><div class="dialog-head"><h3>Gemeinsamer Termin</h3><button type="button" class="icon-btn" id="x">×</button></div><input class="input" name="title" placeholder="Titel" required><div class="form-row"><input class="input" name="date" type="date" required><input class="input" name="time" type="time" required></div><textarea class="input" name="description" rows="3" placeholder="Beschreibung"></textarea><button class="primary">Speichern</button></form>`;document.body.append(d);d.showModal();$('#x').onclick=()=>d.remove();d.querySelector('form').onsubmit=async e=>{e.preventDefault();try{const f=new FormData(e.target);await api(`/api/groups/${id}/events`,{method:'POST',body:JSON.stringify(Object.fromEntries(f))});d.close();d.remove();drawGroup(id);toast('Termin gespeichert')}catch(x){toast(x.message)}}}
async function manageGroup(d){const users=(await api('/api/groups/users')).users;const current=new Set(d.members.map(m=>m.id));const available=users.filter(u=>!current.has(u.id));const add=available.length?prompt('Name des Benutzers zum Hinzufügen:\n\n'+available.map(u=>u.name).join('\n')):'';if(add){const u=available.find(x=>x.name.toLowerCase()===add.trim().toLowerCase());if(u){await api('/api/groups/'+d.group.id+'/members/'+u.id,{method:'POST'});await drawGroup(d.group.id);toast(u.name+' wurde hinzugefügt')}else toast('Benutzer nicht gefunden')}}
async function cloud(){const a=$('#app');a.innerHTML='<div class="loading">Cloud wird geladen …</div>';try{const d=await api('/api/cloud');a.innerHTML=`<div class="section-head"><div><h2>☁ Cloud</h2><div class="muted">Private Dateien und Dateien für deine gesamte Klasse.</div></div><button class="primary" id="uploadFile">＋ Datei hochladen</button></div><div class="card cloud-info"><b>🔒 Privat</b><span class="muted">Nur du kannst die Datei sehen.</span><b>👥 Klasse</b><span class="muted">Alle Mitglieder der ausgewählten Klasse können sie sehen und herunterladen.</span></div><div class="scroll-frame both cloud-scroll"><div class="file-grid">${d.files.length?d.files.map(f=>`<div class="file-card"><div class="file-icon">${fileIcon(f.mime)}</div><h3 title="${esc(f.name)}">${esc(f.name)}</h3><div class="muted">${formatBytes(f.size)} · ${f.scope==='class'?'👥 '+esc(d.classes.find(c=>c.id===f.classId)?.name||'Klasse'):'🔒 Privat'}</div><div class="muted">von ${esc(f.ownerName)}</div><div class="file-actions"><button class="secondary" data-download-file="${f.id}">⬇ Herunterladen</button>${f.ownerId===currentUser.id||currentUser.role==='admin'?`<button class="danger" data-delete-file="${f.id}">Löschen</button>`:''}</div></div>`).join(''):'<div class="card"><div class="muted">Noch keine Dateien vorhanden.</div></div>'}</div></div>`;$('#uploadFile').onclick=()=>openUploadDialog(d.classes);document.querySelectorAll('[data-download-file]').forEach(b=>b.onclick=async()=>{try{const d=await api('/api/cloud/'+b.dataset.downloadFile+'/download');window.location=d.url}catch(e){toast(e.message)}});document.querySelectorAll('[data-delete-file]').forEach(b=>b.onclick=async()=>{if(!confirm('Datei wirklich löschen?'))return;try{await api('/api/cloud/'+b.dataset.deleteFile,{method:'DELETE'});cloud();toast('Datei gelöscht')}catch(e){toast(e.message)}})}catch(e){a.innerHTML=`<div class="card">${esc(e.message)}</div>`}}
function fileIcon(mime){if((mime||'').includes('pdf'))return'📕';if((mime||'').startsWith('image/'))return'🖼️';if((mime||'').includes('word'))return'📝';if((mime||'').includes('sheet')||(mime||'').includes('excel'))return'📊';if((mime||'').includes('presentation')||(mime||'').includes('powerpoint'))return'📽️';return'📄'}
function formatBytes(n){if(n<1024)return n+' B';if(n<1024*1024)return(n/1024).toFixed(0)+' KB';return(n/1024/1024).toFixed(1)+' MB'}
function openUploadDialog(classes){const old=$('#uploadDialog');if(old)old.remove();const d=document.createElement('dialog');d.id='uploadDialog';d.className='dialog';d.innerHTML=`<form class="dialog-card" id="uploadForm"><div class="dialog-head"><h3>Datei teilen</h3><button type="button" class="icon-btn" id="closeUpload">×</button></div><label>Datei<input id="uploadInput" class="input" type="file" required></label><label>Freigabe<select id="uploadScope" class="input"><option value="private">🔒 Nur für mich</option><option value="class">👥 Für die gesamte Klasse</option></select></label><label id="uploadClassLabel">Klasse<select id="uploadClass" class="input">${classes.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></label><div class="muted">Maximal 8 MB pro Datei.</div><button class="primary">Hochladen & teilen</button><div id="uploadError" class="auth-error"></div></form>`;document.body.append(d);d.showModal();$('#uploadScope').onchange=()=>$('#uploadClassLabel').style.display=$('#uploadScope').value==='class'?'grid':'none';$('#uploadScope').dispatchEvent(new Event('change'));$('#closeUpload').onclick=()=>d.close();$('#uploadForm').onsubmit=async e=>{e.preventDefault();const file=$('#uploadInput').files[0];if(!file)return;const reader=new FileReader();reader.onload=async()=>{try{await api('/api/cloud',{method:'POST',body:JSON.stringify({name:file.name,mime:file.type,data:reader.result,scope:$('#uploadScope').value,classId:Number($('#uploadClass').value||0)})});d.close();d.remove();cloud();toast('Datei erfolgreich geteilt')}catch(x){$('#uploadError').textContent=x.message}};reader.readAsDataURL(file)}}
async function calendar(){const a=$('#app');a.innerHTML='<div class="loading">Kalender wird geladen …</div>';try{const d=await api('/api/calendar');const selected=d.classes[0];const now=new Date();const y=now.getFullYear(),m=now.getMonth();const monthLabel=new Intl.DateTimeFormat('de-DE',{month:'long',year:'numeric'}).format(now);const counts={homework:d.events.filter(e=>e.type==='homework').length,appointment:d.events.filter(e=>e.type==='appointment').length,exam:d.events.filter(e=>e.type==='exam').length};a.innerHTML=`<div class="section-head"><div><h2>📅 Klassenkalender</h2><div class="muted">Nur Mitglieder deiner Klasse sehen diese Termine.</div></div><button class="primary" id="newCalendarItem">＋ Eintrag hinzufügen</button></div><div class="calendar-stats"><div class="card"><b>📚 ${counts.homework}</b><span>Hausaufgaben</span></div><div class="card"><b>📌 ${counts.appointment}</b><span>Termine</span></div><div class="card"><b>📝 ${counts.exam}</b><span>Prüfungen</span></div></div><div class="card calendar-card"><div class="calendar-toolbar"><div><h2>${monthLabel}</h2><span class="muted">${d.classes.map(c=>esc(c.name)).join(' · ')}</span></div></div><div class="scroll-frame x calendar-scroll"><div class="calendar-grid">${calendarCells(y,m,d.events)}</div></div></div><div class="section-head"><h2>Einträge</h2></div><div class="event-list">${d.events.length?d.events.map(e=>`<div class="card event-row"><div class="event-type ${e.type}">${eventIcon(e.type)}</div><div class="grow"><b>${esc(e.title)}</b><div class="muted">${eventTypeName(e.type)} · ${e.date} · ${e.time}${e.subject?' · '+esc(e.subject):''}</div>${e.description?`<div class="muted">${esc(e.description)}</div>`:''}<small class="muted">${esc(e.className)} · eingetragen von ${esc(e.creatorName)}</small></div>${e.creatorId===currentUser.id||currentUser.role==='admin'?`<button class="danger" data-delete-event="${e.id}">Löschen</button>`:''}</div>`).join(''):'<div class="card muted">Noch keine Hausaufgaben, Termine oder Prüfungen.</div>'}</div>`;$('#newCalendarItem').onclick=()=>openEventDialog(d.classes);document.querySelectorAll('[data-delete-event]').forEach(b=>b.onclick=async()=>{if(!confirm('Eintrag wirklich löschen?'))return;try{await api('/api/calendar/'+b.dataset.deleteEvent,{method:'DELETE'});calendar();toast('Eintrag gelöscht')}catch(e){toast(e.message)}})}catch(e){a.innerHTML=`<div class="card">${esc(e.message)}</div>`}}
function calendarCells(y,m,events){const names=['Mo','Di','Mi','Do','Fr','Sa','So'];const first=new Date(y,m,1),days=new Date(y,m+1,0).getDate(),start=(first.getDay()+6)%7;let out=names.map(n=>`<div class="day day-head">${n}</div>`).join('');for(let i=0;i<start;i++)out+='<div class="day"></div>';for(let day=1;day<=days;day++){const iso=`${y}-${String(m+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`,today=iso===new Date().toISOString().slice(0,10);out+=`<div class="day ${today?'today':''}"><div class="day-num">${day}</div>${events.filter(e=>e.date===iso).map(e=>`<div class="event ${e.type}" title="${esc(e.title)}">${eventIcon(e.type)} ${esc(e.title)}</div>`).join('')}</div>`}return out}
function eventTypeName(t){return t==='homework'?'Hausaufgabe':t==='exam'?'Prüfung':'Termin'}function eventIcon(t){return t==='homework'?'📚':t==='exam'?'📝':'📌'}
function openEventDialog(classes){const old=$('#eventDialog');if(old)old.remove();const d=document.createElement('dialog');d.id='eventDialog';d.className='dialog';d.innerHTML=`<form class="dialog-card" id="eventForm"><div class="dialog-head"><h3>Klassenkalender</h3><button type="button" class="icon-btn" id="closeEvent">×</button></div><label>Art<select name="type" class="input"><option value="homework">📚 Hausaufgabe</option><option value="appointment">📌 Termin</option><option value="exam">📝 Prüfung</option></select></label><label>Klasse<select name="classId" class="input">${classes.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></label><label>Titel<input name="title" class="input" placeholder="z. B. Mathe S. 84 Nr. 3–6" required></label><div class="form-row"><label>Datum<input name="date" class="input" type="date" required></label><label>Uhrzeit<input name="time" class="input" type="time" required></label></div><label>Fach (optional)<input name="subject" class="input" placeholder="Mathe, Deutsch …"></label><label>Beschreibung (optional)<textarea name="description" class="input" rows="3" placeholder="Weitere Infos …"></textarea><button class="primary">Im Klassenkalender speichern</button><div id="eventError" class="auth-error"></div></form>`;document.body.append(d);d.showModal();$('#closeEvent').onclick=()=>{d.close();d.remove()};$('#eventForm').onsubmit=async e=>{e.preventDefault();try{const f=new FormData(e.target);await api('/api/calendar',{method:'POST',body:JSON.stringify(Object.fromEntries(f))});d.close();d.remove();calendar();toast('Kalendereintrag gespeichert')}catch(x){$('#eventError').textContent=x.message}}}
async function timetable(){
 const el=$('#app');el.innerHTML='<div class="loading">Stundenplan wird geladen …</div>';
 try{
  const d=await api('/api/timetable'),days=['Montag','Dienstag','Mittwoch','Donnerstag','Freitag'];
  const cls=d.classes[0], rows=d.timetable.filter(x=>!cls||x.classId===cls.id);
  const fmt=m=>String(Math.floor(m/60)%24).padStart(2,'0')+':'+String(m%60).padStart(2,'0');
  const setting=(day)=>{const x=(d.settings||[]).find(s=>s.classId===cls?.id&&s.day===day);if(x)return x;return {classId:cls?.id,day,startTime:'08:00',lessonMinutes:45,breakMinutes:15}};
  const timeFor=(day,period)=>{const st=setting(day),[h,mi]=String(st.startTime||'08:00').split(':').map(Number);let start=h*60+mi+(period-1)*(Number(st.lessonMinutes||45)+Number(st.breakMinutes||15));return {start:fmt(start),end:fmt(start+Number(st.lessonMinutes||45))}};
  el.innerHTML=`<div class="section-head"><div><h2>🕐 Stundenplan</h2><div class="muted">${cls?esc(cls.name):'Keine Klasse'} · Mittwoch kann eigene Unterrichts- und Pausenzeiten haben.</div></div></div>
  ${cls?`<div class="scroll-frame x timetable-scroll"><div class="timetable-grid">${days.map((day,i)=>{const n=i+1,st=setting(n),items=rows.filter(x=>x.day===n).sort((x,y)=>x.period-y.period);return `<div class="timetable-day"><h3>${day}</h3><div class="muted small">${esc(st.startTime)} · ${st.lessonMinutes} Min · Pause ${st.breakMinutes} Min</div>${items.length?items.map(x=>{const t=timeFor(n,x.period);return `<div class="lesson"><span class="lesson-time">${t.start}<br><small>${t.end}</small></span><div><b>${esc(x.subject)}</b><div class="muted">${esc(x.teacher||'')} · ${esc(x.room||'')}</div><small class="muted">${esc(cls.name)}</small></div></div>`}).join(''):'<div class="muted">Kein Unterricht.</div>'}</div>`}).join('')}</div></div>
  <div class="card timetable-info"><b>⏱️ Tageszeiten</b><span>Jeder Wochentag hat eigene Zeiten. Mittwoch darf von den anderen Tagen abweichen.</span></div>`:'<div class="card">Du bist noch keiner Klasse zugeordnet.</div>'}`;
 }catch(e){el.innerHTML=`<div class="card">${esc(e.message)}</div>`}
}
function profile(){return `<div class="profile-grid"><div class="card profile-card"><div class="profile-big">${initials(currentUser.name)}</div><h2>${esc(currentUser.name)}</h2><p class="muted">${currentUser.role==='admin'?'Administrator':'Klassenmitglied'}</p></div><div class="card"><h2>Profil</h2><div class="settings-row"><b>Name</b><span>${esc(currentUser.name)}</span></div><div class="settings-row"><b>Rolle</b><span>${esc(currentUser.role)}</span></div></div></div>`}
async function adminView(){
 const a=$('#app');a.innerHTML='<div class="loading">Administration wird geladen …</div>';
 try{
  const [s,u,c,l,t]=await Promise.all([api('/api/admin/stats'),api('/api/admin/users'),api('/api/admin/classes'),api('/api/admin/audit'),api('/api/timetable')]);
  const classes=c.classes||[];
  a.innerHTML=`<div class="section-head"><div><h2>🛡️ Administration</h2><div class="muted">Als Admin hast du die volle Verwaltung über Benutzer, Klassen und Stundenpläne.</div></div><div class="row-actions"><button class="primary" id="newClass">＋ Klasse erstellen</button><button class="secondary" id="refreshAdmin">↻ Aktualisieren</button></div></div>
  <div class="grid">
   <div class="card stat"><span>👤</span><div><b>${s.users}</b><small>Benutzer</small></div></div>
   <div class="card stat"><span>👥</span><div><b>${s.classes}</b><small>Klassen</small></div></div>
   <div class="card stat"><span>💬</span><div><b>${s.messages}</b><small>Nachrichten</small></div></div>
   <div class="card stat"><span>🛡</span><div><b>${s.admins}</b><small>Admins</small></div></div>
  </div>
  <div class="card"><div class="section-head"><div><h2>🏫 Klassen verwalten</h2><div class="muted">Klassen umbenennen, Mitglieder verwalten oder komplett löschen.</div></div></div>
   <div class="scroll-frame y admin-scroll">${classes.map(cl=>`<div class="admin-class"><div class="list-row"><div class="mini-avatar">🏫</div><div class="grow"><b>${esc(cl.name)}</b><div class="muted">${cl.members.length} Mitglieder · ID ${cl.id}</div></div><button class="secondary" data-rename-class="${cl.id}">✏️ Umbenennen</button><button class="danger" data-delete-class="${cl.id}">🗑 Klasse löschen</button></div><div class="member-chips">${cl.members.map(m=>`<span class="chip">${esc(m.name)} <button data-remove="${cl.id}:${m.id}">×</button></span>`).join('')}</div><select data-add="${cl.id}"><option value="">＋ Mitglied hinzufügen …</option>${u.users.filter(x=>x.status==='active'&&!cl.members.some(m=>m.id===x.id)).map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}</select></div>`).join('')||'<div class="muted">Keine Klassen vorhanden.</div>'}</div>
  </div>
  <div class="card"><div class="section-head"><div><h2>🕐 Stundenplan-Editor</h2><div class="muted">Für jeden Tag separat Zeiten einstellen. Mittwoch kann z. B. eine andere Startzeit oder Pause haben.</div></div></div>
   <div class="admin-timetable-toolbar"><label>Klasse<select id="ttClass">${classes.map(cl=>`<option value="${cl.id}">${esc(cl.name)}</option>`).join('')}</select></label><label>Tag<select id="ttDay"><option value="1">Montag</option><option value="2">Dienstag</option><option value="3">Mittwoch</option><option value="4">Donnerstag</option><option value="5">Freitag</option></select></label></div>
   <div id="ttEditor"></div>
  </div>
  <div class="card"><h2>👤 Benutzer & Rechte</h2><div class="scroll-frame y admin-scroll"><div class="admin-users">${u.users.map(x=>`<div class="list-row"><div class="mini-avatar">${initials(x.name)}</div><div class="grow"><b>${esc(x.name)}</b><div class="muted">${x.role} · ${x.status} · ${x.online?'🟢 Online':'⚪ Offline'}</div></div><select data-role="${x.id}"><option value="user" ${x.role==='user'?'selected':''}>User</option><option value="admin" ${x.role==='admin'?'selected':''}>Admin</option></select><select data-status="${x.id}"><option value="active" ${x.status==='active'?'selected':''}>Aktiv</option><option value="banned" ${x.status==='banned'?'selected':''}>Gesperrt</option></select><button class="danger" data-del="${x.id}">Löschen</button></div>`).join('')}</div></div></div>
  <div class="card"><h2>📜 Audit-Log</h2><div class="scroll-frame y admin-scroll"><div class="list">${l.logs.slice().reverse().map(x=>`<div class="list-row"><div class="grow"><b>${esc(x.action)}</b><div class="muted">${esc(x.detail)}</div></div><small class="muted">${new Date(x.createdAt).toLocaleString('de-DE')}</small></div>`).join('')||'<span class="muted">Noch keine Aktionen.</span>'}</div></div></div>`;
  window._adminTimetable=t;
  bindAdmin();
  renderTimetableEditor();
 }catch(e){a.innerHTML=`<div class="card">${esc(e.message)}</div>`}
}
function renderTimetableEditor(){
 const box=$('#ttEditor');if(!box)return;
 const classes=window._adminTimetable?.classes||[];const cid=Number($('#ttClass')?.value||classes[0]?.id),day=Number($('#ttDay')?.value||1);
 const all=window._adminTimetable?.timetable||[],settings=window._adminTimetable?.settings||[];
 const st=settings.find(x=>x.classId===cid&&x.day===day)||{startTime:day===3?'08:00':'08:00',lessonMinutes:45,breakMinutes:day===3?10:15};
 const rows=all.filter(x=>x.classId===cid&&x.day===day).sort((x,y)=>x.period-y.period);
 const fmt=m=>String(Math.floor(m/60)%24).padStart(2,'0')+':'+String(m%60).padStart(2,'0');
 const [hh,mm]=String(st.startTime||'08:00').split(':').map(Number);const times={};for(let p=1;p<=20;p++){let sm=hh*60+mm+(p-1)*(Number(st.lessonMinutes)+Number(st.breakMinutes));times[p]=`${fmt(sm)}–${fmt(sm+Number(st.lessonMinutes))}`}
 box.innerHTML=`<div class="timetable-settings-grid"><label>Startzeit<input class="input" id="ttStart" type="time" value="${esc(st.startTime||'08:00')}"></label><label>Unterricht (Min.)<input class="input" id="ttLesson" type="number" min="1" max="180" value="${st.lessonMinutes||45}"></label><label>Pause (Min.)<input class="input" id="ttBreak" type="number" min="0" max="120" value="${st.breakMinutes||15}"></label><button class="primary" id="saveTtSettings">💾 Tageszeiten speichern</button></div>
  <div class="table-wrap scroll-frame x"><table class="admin-table"><thead><tr><th>Stunde</th><th>Uhrzeit</th><th>Fach</th><th>Lehrer</th><th>Raum</th><th></th></tr></thead><tbody>${Array.from({length:Math.max(6,rows.length)},(_,i)=>{const p=i+1,r=rows.find(x=>x.period===p);return `<tr><td>${p}</td><td>${times[p]}</td><td><input class="input tt-subject" data-period="${p}" value="${esc(r?.subject||'')}" placeholder="Fach"></td><td><input class="input tt-teacher" data-period="${p}" value="${esc(r?.teacher||'')}" placeholder="Lehrer"></td><td><input class="input tt-room" data-period="${p}" value="${esc(r?.room||'')}" placeholder="Raum"></td><td><button class="primary tt-save" data-period="${p}">${r?'💾':'＋'}</button>${r?` <button class="danger tt-delete" data-id="${r.id}">🗑</button>`:''}</td></tr>`}).join('')}</tbody></table></div>`;
 $('#saveTtSettings').onclick=async()=>{try{await api('/api/admin/timetable/settings',{method:'POST',body:JSON.stringify({classId:cid,day,startTime:$('#ttStart').value,lessonMinutes:Number($('#ttLesson').value),breakMinutes:Number($('#ttBreak').value)})});toast('Tageszeiten gespeichert');adminView()}catch(e){toast(e.message)}};
 box.querySelectorAll('.tt-save').forEach(b=>b.onclick=async()=>saveTimetableRow(cid,day,Number(b.dataset.period),null));
 box.querySelectorAll('.tt-delete').forEach(b=>b.onclick=async()=>{if(!confirm('Diese Stunde wirklich löschen?'))return;try{await api('/api/admin/timetable/'+b.dataset.id,{method:'DELETE'});toast('Stunde gelöscht');adminView()}catch(e){toast(e.message)}});
}
async function saveTimetableRow(classId,day,period,id){
 const row=Array.from(document.querySelectorAll(`[data-period="${period}"]`));
 const get=cls=>document.querySelector(`.${cls}[data-period="${period}"]`)?.value.trim()||'';
 const body={classId,day,period,subject:get('tt-subject'),teacher:get('tt-teacher'),room:get('tt-room')};
 if(!body.subject)return toast('Bitte ein Fach eintragen.');
 try{await api('/api/admin/timetable',{method:'POST',body:JSON.stringify(body)});toast('Stunde gespeichert');adminView()}catch(e){toast(e.message)}
}
function bindAdmin(){
 const nc=$('#newClass');if(nc)nc.onclick=async()=>{const name=prompt('Klassenname, z. B. 8A');if(name?.trim())try{await api('/api/admin/classes',{method:'POST',body:JSON.stringify({name:name.trim()})});adminView()}catch(e){toast(e.message)}};
 const ref=$('#refreshAdmin');if(ref)ref.onclick=()=>adminView();
 document.querySelectorAll('[data-rename-class]').forEach(b=>b.onclick=async()=>{const name=prompt('Neuer Klassenname:');if(!name?.trim())return;try{await api('/api/admin/classes/'+b.dataset.renameClass,{method:'PATCH',body:JSON.stringify({name:name.trim()})});toast('Klasse umbenannt');adminView()}catch(e){toast(e.message)}});
 document.querySelectorAll('[data-delete-class]').forEach(b=>b.onclick=async()=>{if(!confirm('ACHTUNG: Klasse, Mitgliederzuordnungen, Klassenchat, Stundenplan, Klassendateien und Klassentermine werden gelöscht. Wirklich fortfahren?'))return;try{await api('/api/admin/classes/'+b.dataset.deleteClass,{method:'DELETE'});toast('Klasse gelöscht');adminView()}catch(e){toast(e.message)}});
 document.querySelectorAll('[data-role]').forEach(s=>s.onchange=async()=>{try{await api('/api/admin/users/'+s.dataset.role,{method:'PATCH',body:JSON.stringify({role:s.value})});toast('Rolle gespeichert')}catch(e){toast(e.message);adminView()}});
 document.querySelectorAll('[data-status]').forEach(s=>s.onchange=async()=>{try{await api('/api/admin/users/'+s.dataset.status,{method:'PATCH',body:JSON.stringify({status:s.value})});toast('Status gespeichert')}catch(e){toast(e.message);adminView()}});
 document.querySelectorAll('[data-del]').forEach(b=>b.onclick=async()=>{if(!confirm('Benutzer wirklich löschen?'))return;try{await api('/api/admin/users/'+b.dataset.del,{method:'DELETE'});adminView()}catch(e){toast(e.message)}});
 document.querySelectorAll('[data-add]').forEach(s=>s.onchange=async()=>{if(!s.value)return;try{await api(`/api/admin/classes/${s.dataset.add}/members/${s.value}`,{method:'POST'});adminView()}catch(e){toast(e.message)}});
 document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=async()=>{const [c,u]=b.dataset.remove.split(':');try{await api(`/api/admin/classes/${c}/members/${u}`,{method:'DELETE'});adminView()}catch(e){toast(e.message)}});
 const tc=$('#ttClass'),td=$('#ttDay');if(tc)tc.onchange=renderTimetableEditor;if(td)td.onchange=renderTimetableEditor;
}
function bind(){document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>setView(b.dataset.go));document.querySelectorAll('[data-class]').forEach(b=>b.onclick=async()=>{await openClass(Number(b.dataset.class));renderSidebarActive()});document.querySelectorAll('[data-user]').forEach(b=>b.onclick=async()=>{await openPrivate(Number(b.dataset.user));renderSidebarActive()});document.querySelectorAll('[data-group]').forEach(b=>b.onclick=async()=>{await openGroup(Number(b.dataset.group));renderSidebarActive()});const ng=$('#newGroup');if(ng)ng.onclick=async()=>{const name=prompt('Name der neuen Gruppe:');if(!name?.trim())return;const users=(await api('/api/groups/users')).users;const selected=prompt('Mitglieder hinzufügen (Namen mit Komma trennen):\n\n'+users.map(u=>u.name).join('\n'));const names=(selected||'').split(',').map(x=>x.trim().toLowerCase()).filter(Boolean);const ids=users.filter(u=>names.includes(u.name.toLowerCase())).map(u=>u.id);try{const d=await api('/api/groups',{method:'POST',body:JSON.stringify({name:name.trim(),memberIds:ids})});selectedGroup=d.group.id;chatMode='group';chatView();toast('Gruppe erstellt')}catch(e){toast(e.message)}};const np=$('#newPrivate');if(np)np.onclick=()=>{const users=window.chatUsers||[];if(!users.length)return toast('Keine anderen aktiven Benutzer verfügbar.');const name=prompt('Name des Benutzers eingeben:\n\n'+users.map(u=>u.name).join('\n'));const u=users.find(x=>x.name.toLowerCase()===String(name||'').trim().toLowerCase());if(u){openPrivate(u.id)}else if(name)toast('Benutzer nicht gefunden.');};}
function renderSidebarActive(){}
const sidebarKey='klassencloud-sidebar-collapsed';if(localStorage.getItem(sidebarKey)==='1')document.body.classList.add('sidebar-collapsed');const sidebarToggleEl=$('#sidebarToggle');if(sidebarToggleEl)sidebarToggleEl.onclick=()=>{const collapsed=document.body.classList.toggle('sidebar-collapsed');localStorage.setItem(sidebarKey,collapsed?'1':'0')};const loginTabEl=$('#loginTab'),registerTabEl=$('#registerTab'),loginFormEl=$('#loginForm'),registerFormEl=$('#registerForm'),loginErrorEl=$('#loginError'),registerErrorEl=$('#registerError');document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{setView(b.dataset.view);if(window.innerWidth<=720)$('#sidebar').classList.remove('open')});$('#mobileMenu').onclick=()=>$('#sidebar').classList.toggle('open');$('#profileQuick').onclick=()=>setView('profile');$('#themeBtn').onclick=()=>{state.theme=state.theme==='dark'?'light':'dark';render()};$('#logoutBtn').onclick=async()=>{await api('/api/logout',{method:'POST'});currentUser=null;showAuth()};loginTabEl.onclick=()=>{loginTabEl.classList.add('active');registerTabEl.classList.remove('active');loginFormEl.hidden=false;registerFormEl.hidden=true;loginErrorEl.textContent=''};registerTabEl.onclick=()=>{registerTabEl.classList.add('active');loginTabEl.classList.remove('active');registerFormEl.hidden=false;loginFormEl.hidden=true;registerErrorEl.textContent=''};loginFormEl.onsubmit=async e=>{e.preventDefault();loginErrorEl.textContent='';try{const f=new FormData(e.target),d=await api('/api/login',{method:'POST',body:JSON.stringify(Object.fromEntries(f))});currentUser=d.user;enter()}catch(x){loginErrorEl.textContent=x.message}};registerFormEl.onsubmit=async e=>{e.preventDefault();registerErrorEl.textContent='';try{const f=new FormData(e.target),d=await api('/api/register',{method:'POST',body:JSON.stringify(Object.fromEntries(f))});currentUser=d.user;enter()}catch(x){registerErrorEl.textContent=x.message}};boot();
