const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto'),url=require('url');
const { createClient } = require('@supabase/supabase-js');
let webpush=null;try{webpush=require('web-push')}catch{}
const ROOT=__dirname;
const SUPABASE_URL=process.env.SUPABASE_URL;
const SUPABASE_SERVICE_ROLE_KEY=process.env.SUPABASE_SERVICE_ROLE_KEY;
const SUPABASE_BUCKET=process.env.SUPABASE_BUCKET||'klassencloud-files';
if(!SUPABASE_URL||!SUPABASE_SERVICE_ROLE_KEY){console.error('Fehlende Umgebungsvariablen: SUPABASE_URL und SUPABASE_SERVICE_ROLE_KEY');process.exit(1)}
const supabase=createClient(SUPABASE_URL,SUPABASE_SERVICE_ROLE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.webmanifest':'application/manifest+json','.png':'image/png','.ico':'image/x-icon','.svg':'image/svg+xml'};
const empty={users:[],classes:[],memberships:[],chats:[],messages:[],groups:[],groupMembers:[],audit:[],files:[],events:[],groupFiles:[],groupEvents:[],timetable:[],timetableSettings:[],sessions:[],uploadCodes:[],pushSubscriptions:[],announcements:[],privateBlocks:[]};
let db=structuredClone(empty);
let persistTimer=null,persistRunning=false,persistAgain=false;
async function loadDB(){const {data,error}=await supabase.from('app_state').select('state').eq('id',1).maybeSingle();if(error)throw error;if(data?.state){db={...structuredClone(empty),...data.state};for(const k of Object.keys(empty))if(!Array.isArray(db[k]))db[k]=[]}else await persist();}
async function persist(){if(persistRunning){persistAgain=true;return}persistRunning=true;try{const {error}=await supabase.from('app_state').upsert({id:1,state:db,updated_at:new Date().toISOString()},{onConflict:'id'});if(error)throw error}catch(e){console.error('Supabase-Speicherung fehlgeschlagen:',e.message)}finally{persistRunning=false;if(persistAgain){persistAgain=false;persist()}}}
function save(){clearTimeout(persistTimer);persistTimer=setTimeout(()=>persist(),80)}
async function ensureBucket(){const {data}=await supabase.storage.listBuckets();if(!data?.some(b=>b.name===SUPABASE_BUCKET)){const {error}=await supabase.storage.createBucket(SUPABASE_BUCKET,{public:false,fileSizeLimit:50*1024*1024});if(error&&!/already exists/i.test(error.message))throw error}else{const {error}=await supabase.storage.updateBucket(SUPABASE_BUCKET,{public:false,fileSizeLimit:50*1024*1024});if(error)console.warn('Storage-Bucket konnte nicht auf 50 MB aktualisiert werden:',error.message)}}
function hash(password,salt=crypto.randomBytes(16).toString('hex')){return {salt,hash:crypto.scryptSync(password,salt,64).toString('hex')}}
function seed(){let changed=false;if(!db.classes.length){db.classes.push({id:1,name:'8A',ownerId:null,createdAt:new Date().toISOString()});db.classes.push({id:2,name:'10B',ownerId:null,createdAt:new Date().toISOString()});changed=true}const bootstrap=String(process.env.ADMIN_BOOTSTRAP_PASSWORD||'');if(!db.users.length&&bootstrap.length>=8){const h=hash(bootstrap),admin={id:1,name:'Administrator',passwordHash:h.hash,passwordSalt:h.salt,role:'admin',status:'active',lastSeen:Date.now(),createdAt:new Date().toISOString()};db.users.push(admin);const cls=db.classes.find(c=>c.id===1);if(cls)cls.ownerId=admin.id;db.memberships.push({userId:admin.id,classId:1,role:'admin'});db.groups.push({id:1,name:'8A – Klassengruppe',ownerId:admin.id,createdAt:new Date().toISOString()});db.groupMembers.push({groupId:1,userId:admin.id,role:'owner'});changed=true}return changed}
function addMinutes(time,mins){const [h,m]=String(time||'08:00').split(':').map(Number);let x=h*60+m+Number(mins||0);x=((x%1440)+1440)%1440;return String(Math.floor(x/60)).padStart(2,'0')+':'+String(x%60).padStart(2,'0')}
function seedClassTimetable(classId,variant=0){
 const subjects=[
  [['Mathematik','Herr Müller','204'],['Deutsch','Frau Weber','201'],['Englisch','Herr Klein','203'],['Biologie','Frau Lang','105'],['Sport','Herr Bauer','Turnhalle'],['Geschichte','Frau Roth','202']],
  [['Deutsch','Frau Weber','201'],['Mathematik','Herr Müller','204'],['Physik','Herr Sommer','106'],['Kunst','Frau König','107'],['Englisch','Herr Klein','203'],['Musik','Frau Wolf','Aula']]
 ][variant%2];
 const dayStarts=[['08:00',[45,45,45,45,45,45],[10,15,20,15,10]],['08:00',[45,45,45,45,45,45],[15,10,20,15,15]],['08:15',[45,45,45,45,45,45],[10,20,15,25,10]],['08:00',[45,45,45,45,45,45],[15,10,20,15,15]],['08:00',[45,45,45,45,45,45],[10,15,20,15,10]]];
 for(let day=1;day<=5;day++){
   let cur=dayStarts[day-1][0];
   for(let period=1;period<=6;period++){
     const x=subjects[(day-1+variant)%subjects.length][(period-1)%6];
     const mins=dayStarts[day-1][1][period-1], end=addMinutes(cur,mins);
     db.timetable.push({id:Date.now()+Math.random(),classId,day,period,startTime:cur,endTime:end,subject:x[0],teacher:x[1],room:x[2]});
     cur=addMinutes(end,dayStarts[day-1][2][period-1]);
   }
 }
}
function migrateTimetableTimes(){
 for(const t of db.timetable){
   if(t.startTime&&t.endTime)continue;
   const st=db.timetableSettings.find(x=>x.classId===t.classId&&x.day===t.day)||{startTime:'08:00',lessonMinutes:45,breakMinutes:15};
   t.startTime=addMinutes(st.startTime,(t.period-1)*(Number(st.lessonMinutes||45)+Number(st.breakMinutes||15)));
   t.endTime=addMinutes(t.startTime,Number(st.lessonMinutes||45));
 }
}
function seedTimetable(){
 migrateTimetableTimes();
 let changed=false;
 db.classes.forEach((c,i)=>{if(!db.timetable.some(t=>t.classId===c.id)){seedClassTimetable(c.id,i);changed=true;}});
 return changed;
}
const sessions=new Map(),typingState=new Map();
const nowMs=()=>Date.now();
function isOnline(u){return !!u&&!!u.lastSeen&&nowMs()-u.lastSeen<120000}
function send(res,status,data,headers={}){res.writeHead(status,{'Content-Type':typeof data==='string'?'text/plain; charset=utf-8':'application/json; charset=utf-8','Cache-Control':'no-store',...headers});res.end(typeof data==='string'?data:JSON.stringify(data))}
function cookies(req){return Object.fromEntries((req.headers.cookie||'').split(';').filter(Boolean).map(x=>{const i=x.indexOf('=');return [x.slice(0,i).trim(),decodeURIComponent(x.slice(i+1))]}))}
function me(req){const sid=cookies(req).sid,rec=db.sessions.find(x=>x.sid===sid&&x.expiresAt>Date.now()),u=rec&&db.users.find(u=>u.id===rec.userId&&u.status==='active');if(u){u.lastSeen=nowMs();}return u}
function pub(u){const mod=u.moderation||{};return {id:u.id,name:mod.nameHidden?'Unbenannt':u.name,role:u.role,status:u.status,online:isOnline(u),lastSeen:u.lastSeen||null,createdAt:u.createdAt,bio:mod.bioHidden?'':(u.bio||''),avatarColor:u.avatarColor||null,avatarEmoji:mod.avatarHidden?'':(u.avatarEmoji||''),avatarMode:u.avatarMode||'letter',moderation:{nameHidden:!!mod.nameHidden,bioHidden:!!mod.bioHidden,avatarHidden:!!mod.avatarHidden},preferences:u.preferences||{}}}
function parse(req){return new Promise((resolve,reject)=>{let b='';req.on('data',c=>{b+=c;if(b.length>70e6){req.destroy();reject(new Error('Payload zu groß'))}});req.on('end',()=>{try{resolve(b?JSON.parse(b):{})}catch{resolve({})}});req.on('error',reject)})}
function auth(req,res){const u=me(req);if(!u){send(res,401,{error:'Nicht eingeloggt'});return null}return u}
function admin(req,res){const u=auth(req,res);if(!u)return null;if(u.role!=='admin'){send(res,403,{error:'Nur Administratoren dürfen das.'});return null}return u}
function member(userId,classId){return db.memberships.some(m=>m.userId===userId&&m.classId===classId)}
function audit(uid,action,detail){db.audit.unshift({id:Date.now()+Math.random(),adminId:uid,action,detail,createdAt:new Date().toISOString()});db.audit=db.audit.slice(0,500)}
function privateBlocked(a,b){
 if(!a||!b)return false;
 return db.privateBlocks.some(x=>(x.userA===a.id&&x.userB===b.id)||(x.userA===b.id&&x.userB===a.id));
}
function privateAllowed(a,b){return a&&b&&a.id!==b.id&&a.status==='active'&&b.status==='active'&&!privateBlocked(a,b)}
function chatForUsers(a,b){let c=db.chats.find(x=>x.type==='private'&&((x.userA===a&&x.userB===b)||(x.userA===b&&x.userB===a)));if(!c){c={id:Date.now()+Math.random(),type:'private',userA:a,userB:b,createdAt:new Date().toISOString()};db.chats.push(c);save()}return c}
function messagePublic(m){
 const u=db.users.find(x=>x.id===m.userId);
 const reactions=Array.isArray(m.reactions)?m.reactions:[]; const grouped={}; for(const r of reactions){if(!grouped[r.emoji])grouped[r.emoji]={emoji:r.emoji,count:0,userIds:[]};grouped[r.emoji].count++;grouped[r.emoji].userIds.push(r.userId)} return {id:m.id,userId:m.userId,userName:u?.name||'Unbekannt',text:m.text||'',attachment:m.attachment||null,reactions:Object.values(grouped),createdAt:m.createdAt};
}
async function createChatMessage(u,type,chatId,b){
 const text=String(b.text||'').trim();
 const media=b.media&&typeof b.media==='object'?b.media:null;
 if(!text&&!media)return {error:'Nachricht ist leer.'};
 if(text.length>2000)return {error:'Nachricht ist zu lang.'};
 const msg={id:Date.now()+Math.random(),chatType:type,chatId,userId:u.id,text,createdAt:new Date().toISOString()};
 if(media){
   const data=String(media.data||''),mime=String(media.mime||'application/octet-stream'),name=String(media.name||'Anhang');
   if(!data.includes(','))return {error:'Anhang ist ungültig.'};
   const raw=Buffer.from(data.split(',')[1],'base64');
   const max=15*1024*1024;
   if(raw.length>max)return {error:'Bilder und Sprachnachrichten dürfen maximal 15 MB groß sein.'};
   const isImage=/^image\//i.test(mime),isAudio=/^audio\//i.test(mime);
   if(!isImage&&!isAudio)return {error:'Im Chat sind nur Bilder und Sprachnachrichten erlaubt.'};
   const stored=crypto.randomBytes(16).toString('hex')+path.extname(name).slice(0,12).replace(/[^a-zA-Z0-9.]/g,'');
   const storageKey=storagePath('chat',msg.id,stored);
   try{await uploadToStorage(raw,storageKey,mime)}catch(e){return {error:'Anhang konnte nicht gespeichert werden.'}};
   msg.attachment={name,mime,size:raw.length,kind:isImage?'image':'audio',storageKey};
 }
 db.messages.push(msg);save();
 return {message:msg};
}
function filePublic(f){return {id:f.id,name:f.name,size:f.size,mime:f.mime,scope:f.scope,classId:f.classId||null,ownerId:f.ownerId,ownerName:db.users.find(u=>u.id===f.ownerId)?.name||'Unbekannt',createdAt:f.createdAt}}
function eventPublic(e){return {...e,creatorName:db.users.find(u=>u.id===e.creatorId)?.name||'Unbekannt',className:e.classId?db.classes.find(c=>c.id===e.classId)?.name||'Unbekannt':null}}
function groupFilePublic(f){return {...f,ownerName:db.users.find(u=>u.id===f.ownerId)?.name||'Unbekannt'}}
function groupEventPublic(e){return {...e,creatorName:db.users.find(u=>u.id===e.creatorId)?.name||'Unbekannt'}}
function groupMember(u,gid){return db.groupMembers.some(m=>m.groupId===gid&&m.userId===u.id)}
function typingKey(type,id){return `${type}:${id}`}
function typingUsers(type,id,currentId){const key=typingKey(type,id),now=nowMs(),arr=typingState.get(key)||[];const live=arr.filter(x=>now-x.at<4000);typingState.set(key,live);return live.filter(x=>x.userId!==currentId).map(x=>{const u=db.users.find(y=>y.id===x.userId);return u?pub(u):null}).filter(Boolean)}
function storagePath(kind,id,stored){return `${kind}/${id}/${stored}`}
async function uploadToStorage(raw,storageKey,mimeType){const {error}=await supabase.storage.from(SUPABASE_BUCKET).upload(storageKey,raw,{contentType:mimeType||'application/octet-stream',upsert:false});if(error)throw error}
async function signedDownload(storageKey){const {data,error}=await supabase.storage.from(SUPABASE_BUCKET).createSignedUrl(storageKey,60);if(error)throw error;return data.signedUrl}
async function deleteStorage(storageKey){if(storageKey)await supabase.storage.from(SUPABASE_BUCKET).remove([storageKey])}
function vapidConfigured(){return !!(webpush&&process.env.VAPID_PUBLIC_KEY&&process.env.VAPID_PRIVATE_KEY&&process.env.VAPID_SUBJECT)}
if(vapidConfigured())webpush.setVapidDetails(process.env.VAPID_SUBJECT,process.env.VAPID_PUBLIC_KEY,process.env.VAPID_PRIVATE_KEY);
async function pushToUser(userId,payload){if(!vapidConfigured())return;const subs=db.pushSubscriptions.filter(x=>x.userId===userId);for(const sub of subs){try{await webpush.sendNotification(sub.subscription,JSON.stringify(payload))}catch(e){if(e.statusCode===404||e.statusCode===410)db.pushSubscriptions=db.pushSubscriptions.filter(x=>x.id!==sub.id);else console.warn('Push fehlgeschlagen:',e.message)}}save()}
async function pushToChatRecipients(senderId,type,chatId,title,text){const ids=new Set();if(type==='private'){const c=db.chats.find(x=>x.id===chatId);if(c){if(c.userA!==senderId)ids.add(c.userA);if(c.userB!==senderId)ids.add(c.userB)}}else if(type==='class'){for(const m of db.memberships.filter(x=>x.classId===chatId))if(m.userId!==senderId)ids.add(m.userId)}else if(type==='group'){for(const m of db.groupMembers.filter(x=>x.groupId===chatId))if(m.userId!==senderId)ids.add(m.userId)}await Promise.all([...ids].map(id=>pushToUser(id,{title,text,url:'/',badgeCount:1,tag:`chat-${type}-${chatId}`})))}
async function api(req,res,p){
 if(req.method==='GET'&&p==='/api/health')return send(res,200,{ok:true,app:'KlassenCloud',version:'V15',storage:'supabase'});

 if(req.method==='POST'&&p==='/api/register'){const b=await parse(req),name=String(b.name||'').trim(),pw=String(b.password||'');if(name.length<2||name.length>40||pw.length<8)return send(res,400,{error:'Name (2–40 Zeichen) und Passwort (mind. 8 Zeichen) erforderlich.'});if(!/^[\p{L}\p{N} ._'-]+$/u.test(name))return send(res,400,{error:'Der Name enthält ungültige Zeichen.'});if(db.users.some(u=>u.name.toLowerCase()===name.toLowerCase()))return send(res,400,{error:'Dieser Name ist bereits vergeben.'});const h=hash(pw),u={id:Date.now(),name,passwordHash:h.hash,passwordSalt:h.salt,role:'user',status:'active',createdAt:new Date().toISOString()};db.users.push(u);const className=String(b.className||'8A').trim();const cls=db.classes.find(c=>c.name.toLowerCase()===className.toLowerCase());if(!cls)return send(res,400,{error:'Diese Klasse gibt es nicht. Bitte wähle eine vorhandene Klasse.'});db.memberships.push({userId:u.id,classId:cls.id,role:'member'});save();return loginResponse(res,u)}
 if(req.method==='POST'&&p==='/api/login'){const b=await parse(req),name=String(b.name||'').trim(),u=db.users.find(x=>x.name.toLowerCase()===name.toLowerCase());if(!u||u.status!=='active')return send(res,401,{error:'Name oder Passwort falsch.'});const got=hash(String(b.password||''),u.passwordSalt).hash;if(!crypto.timingSafeEqual(Buffer.from(got,'hex'),Buffer.from(u.passwordHash,'hex')))return send(res,401,{error:'Name oder Passwort falsch.'});return loginResponse(res,u)}
 if(req.method==='POST'&&p==='/api/logout'){const c=cookies(req);if(c.sid){sessions.delete(c.sid);db.sessions=db.sessions.filter(x=>x.sid!==c.sid);save()}return send(res,200,{ok:true},{'Set-Cookie':'sid=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0'})}
 if(req.method==='GET'&&p==='/api/me'){const u=auth(req,res);if(!u)return;return send(res,200,{user:pub(u)})}
 if(req.method==='PATCH'&&p==='/api/profile'){const u=auth(req,res);if(!u)return;const b=await parse(req);const name=String(b.name??u.name).trim();const bio=String(b.bio??u.bio??'').trim();const avatarColor=String(b.avatarColor??u.avatarColor??'').trim();const avatarEmoji=String(b.avatarEmoji??u.avatarEmoji??'').trim().slice(0,32);const avatarMode=['letter','emoji'].includes(b.avatarMode)?b.avatarMode:(u.avatarMode||'letter');if(name.length<2||name.length>40)return send(res,400,{error:'Name muss 2–40 Zeichen lang sein.'});if(!/^[\p{L}\p{N} ._'-]+$/u.test(name))return send(res,400,{error:'Der Name enthält ungültige Zeichen.'});if(db.users.some(x=>x.id!==u.id&&x.name.toLowerCase()===name.toLowerCase()))return send(res,400,{error:'Dieser Name ist bereits vergeben.'});u.name=name;u.bio=bio.slice(0,160);u.avatarColor=/^#[0-9a-fA-F]{6}$/.test(avatarColor)?avatarColor:null;u.avatarEmoji=avatarEmoji;u.avatarMode=avatarMode;u.preferences=(b.preferences&&typeof b.preferences==='object')?b.preferences:u.preferences||{};save();return send(res,200,{user:pub(u)})}
 if(req.method==='POST'&&p==='/api/presence'){const u=auth(req,res);if(!u)return;u.lastSeen=nowMs();save();return send(res,200,{online:true})}
 const tm=p.match(/^\/api\/typing\/(class|private|group)\/([0-9]+(?:\.[0-9]+)?)$/);if(tm){const u=auth(req,res);if(!u)return;const type=tm[1],id=Number(tm[2]);if(type==='class'&&!member(u.id,id)&&u.role!=='admin')return send(res,403,{error:'Kein Zugriff.'});if(type==='group'&&!groupMember(u,id)&&u.role!=='admin')return send(res,403,{error:'Kein Zugriff.'});if(type==='private'){const other=db.users.find(x=>x.id===id);if(!privateAllowed(u,other))return send(res,403,{error:'Kein Zugriff.'})}const key=typingKey(type,id);if(req.method==='POST'){const b=await parse(req),on=!!b.typing;let arr=(typingState.get(key)||[]).filter(x=>x.userId!==u.id);if(on)arr.push({userId:u.id,at:nowMs()});typingState.set(key,arr);return send(res,200,{ok:true})}return send(res,200,{users:typingUsers(type,id,u.id)})}

 if(req.method==='GET'&&p==='/api/classes'){const u=auth(req,res);if(!u)return;const own=db.memberships.filter(m=>m.userId===u.id).map(m=>db.classes.find(c=>c.id===m.classId)).filter(Boolean);return send(res,200,{classes:own})}
 if(req.method==='GET'&&p==='/api/push/config')return send(res,200,{enabled:vapidConfigured(),publicKey:process.env.VAPID_PUBLIC_KEY||null});
 if(req.method==='POST'&&p==='/api/push/subscribe'){const u=auth(req,res);if(!u)return;const b=await parse(req);const sub=b.subscription;if(!sub||!sub.endpoint||!sub.keys)return send(res,400,{error:'Push-Abonnement ungültig.'});db.pushSubscriptions=db.pushSubscriptions.filter(x=>x.userId!==u.id||x.subscription?.endpoint!==sub.endpoint);db.pushSubscriptions.push({id:crypto.randomUUID(),userId:u.id,subscription:sub,createdAt:new Date().toISOString()});save();return send(res,200,{ok:true,enabled:vapidConfigured()})}
 if(req.method==='POST'&&p==='/api/push/unsubscribe'){const u=auth(req,res);if(!u)return;const b=await parse(req);const endpoint=String(b.endpoint||'');db.pushSubscriptions=db.pushSubscriptions.filter(x=>!(x.userId===u.id&&x.subscription?.endpoint===endpoint));save();return send(res,200,{ok:true})}
 if(req.method==='POST'&&p==='/api/chat/notifications/read'){const u=auth(req,res);if(!u)return;const seen={};for(const c of db.classes)if(member(u.id,c.id)||u.role==='admin'){const m=db.messages.filter(x=>x.chatType==='class'&&x.chatId===c.id&&x.userId!==u.id).slice(-1)[0];if(m)seen['class:'+c.id]=new Date(m.createdAt).getTime();}for(const g of db.groups)if(groupMember(u,g.id)||u.role==='admin'){const m=db.messages.filter(x=>x.chatType==='group'&&x.chatId===g.id&&x.userId!==u.id).slice(-1)[0];if(m)seen['group:'+g.id]=new Date(m.createdAt).getTime();}for(const c of db.chats.filter(c=>c.type==='private'&&(c.userA===u.id||c.userB===u.id))){const m=db.messages.filter(x=>x.chatType==='private'&&x.chatId===c.id&&x.userId!==u.id).slice(-1)[0];if(m)seen['private:'+c.id]=new Date(m.createdAt).getTime();}return send(res,200,{ok:true,seen})}
 if(req.method==='GET'&&p==='/api/chat/notifications'){const u=auth(req,res);if(!u)return;const allowed=[];for(const c of db.classes)if(member(u.id,c.id)||u.role==='admin')allowed.push({type:'class',id:c.id,title:c.name});for(const g of db.groups)if(groupMember(u,g.id)||u.role==='admin')allowed.push({type:'group',id:g.id,title:g.name});for(const c of db.chats.filter(c=>c.type==='private'&&(c.userA===u.id||c.userB===u.id))){const otherId=c.userA===u.id?c.userB:c.userA,other=db.users.find(x=>x.id===otherId);if(other)allowed.push({type:'private',id:c.id,title:other.name});}const seen={};try{Object.assign(seen,JSON.parse(String(req.headers['x-notify-seen']||'{}')))}catch{}let fresh=[];for(const a of allowed){const ms=db.messages.filter(m=>m.chatType===a.type&&m.chatId===a.id&&m.userId!==u.id).slice(-100);for(const m of ms)if(!seen[a.type+':'+a.id]||new Date(m.createdAt).getTime()>Number(seen[a.type+':'+a.id]))fresh.push({id:m.id,title:a.title,text:m.text,createdAt:m.createdAt,type:a.type,chatId:a.id});}fresh.sort((a,b)=>new Date(a.createdAt)-new Date(b.createdAt));return send(res,200,{unread:fresh.length,newMessages:fresh.slice(-5)})}
 if(req.method==='GET'&&p==='/api/chat/overview'){const u=auth(req,res);if(!u)return;const classes=db.classes.filter(c=>member(u.id,c.id)||u.role==='admin').map(c=>({id:c.id,name:c.name,memberCount:db.memberships.filter(m=>m.classId===c.id).length}));const privateChats=db.chats.filter(c=>c.type==='private'&&(c.userA===u.id||c.userB===u.id)).map(c=>{const otherId=c.userA===u.id?c.userB:c.userA;const other=db.users.find(x=>x.id===otherId);return {id:c.id,other:other&&pub(other)}}).filter(x=>x.other);return send(res,200,{classes,privateChats})}
 const cm=p.match(/^\/api\/chat\/class\/([0-9]+(?:\.[0-9]+)?)$/);if(cm){const u=auth(req,res);if(!u)return;const cid=Number(cm[1]);if(!db.classes.some(c=>c.id===cid))return send(res,404,{error:'Klasse nicht gefunden'});if(!member(u.id,cid)&&u.role!=='admin')return send(res,403,{error:'Du bist nicht Mitglied dieses Klassenchats.'});if(req.method==='GET'){const messages=db.messages.filter(m=>m.chatType==='class'&&m.chatId===cid).slice(-300).map(messagePublic);return send(res,200,{class:db.classes.find(c=>c.id===cid),messages,typing:typingUsers('class',cid,u.id)})}if(req.method==='POST'){
  const b=await parse(req),r=await createChatMessage(u,'class',cid,b);
  if(r.error)return send(res,400,{error:r.error});
  pushToChatRecipients(u.id,'class',cid,db.classes.find(x=>x.id===cid)?.name||'Neue Nachricht',r.message.text||'📎 Neuer Anhang').catch(()=>{});
  return send(res,200,{ok:true,message:messagePublic(r.message)});
}}
 const pm=p.match(/^\/api\/chat\/private\/([0-9]+(?:\.[0-9]+)?)$/);if(pm){const u=auth(req,res);if(!u)return;const otherId=Number(pm[1]),other=db.users.find(x=>x.id===otherId);if(!privateAllowed(u,other))return send(res,404,{error:'Dieser Benutzer ist nicht verfügbar.'});const c=chatForUsers(u.id,other.id);if(req.method==='GET'){return send(res,200,{chat:{id:c.id,other:pub(other)},messages:db.messages.filter(m=>m.chatType==='private'&&m.chatId===c.id).slice(-300).map(messagePublic),typing:typingUsers('private',other.id,u.id)})}if(req.method==='POST'){
  const b=await parse(req),r=await createChatMessage(u,'private',c.id,b);
  if(r.error)return send(res,400,{error:r.error});
  pushToChatRecipients(u.id,'private',c.id,other.name,r.message.text||'📎 Neuer Anhang').catch(()=>{});
  return send(res,200,{ok:true,message:messagePublic(r.message)});
}}
 if(req.method==='GET'&&p==='/api/chat/users'){const u=auth(req,res);if(!u)return;const users=db.users.filter(x=>x.id!==u.id&&x.status==='active').map(pub);return send(res,200,{users})}
  const searchPath=p.match(/^\/api\/chat\/search\/(class|private|group)\/([0-9]+(?:\.[0-9]+)?)$/);if(searchPath&&req.method==='GET'){const u=auth(req,res);if(!u)return;const type=searchPath[1],id=Number(searchPath[2]),q=(new URL(req.url,'http://localhost')).searchParams.get('q')?.trim().toLowerCase()||'';if(q.length<2)return send(res,200,{messages:[]});let msgs=[];if(type==='class'){if(!member(u.id,id)&&u.role!=='admin')return send(res,403,{error:'Kein Zugriff.'});msgs=db.messages.filter(m=>m.chatType==='class'&&m.chatId===id)}else if(type==='group'){if(!groupMember(u,id)&&u.role!=='admin')return send(res,403,{error:'Kein Zugriff.'});msgs=db.messages.filter(m=>m.chatType==='group'&&m.chatId===id)}else{const other=db.users.find(x=>x.id===id);if(!privateAllowed(u,other))return send(res,403,{error:'Kein Zugriff.'});const c=chatForUsers(u.id,other.id);msgs=db.messages.filter(m=>m.chatType==='private'&&m.chatId===c.id)}return send(res,200,{messages:msgs.filter(m=>m.text.toLowerCase().includes(q)).slice(-100).map(messagePublic)})}
 // GROUP CHATS: private groups with owner/member permissions
 if(req.method==='GET'&&p==='/api/groups'){const u=auth(req,res);if(!u)return;const groups=db.groups.filter(g=>u.role==='admin'||db.groupMembers.some(m=>m.groupId===g.id&&m.userId===u.id)).map(g=>({...g,ownerName:db.users.find(x=>x.id===g.ownerId)?.name||'Unbekannt',memberCount:db.groupMembers.filter(m=>m.groupId===g.id).length,members:db.groupMembers.filter(m=>m.groupId===g.id).map(m=>{const x=db.users.find(u=>u.id===m.userId);return x?{...pub(x),groupRole:m.role}:null}).filter(Boolean)}));return send(res,200,{groups})}
 if(req.method==='POST'&&p==='/api/groups'){const u=auth(req,res);if(!u)return;const b=await parse(req),name=String(b.name||'').trim();if(name.length<2||name.length>60)return send(res,400,{error:'Gruppenname muss 2–60 Zeichen lang sein.'});const g={id:Date.now(),name,ownerId:u.id,createdAt:new Date().toISOString()};db.groups.push(g);db.groupMembers.push({groupId:g.id,userId:u.id,role:'owner'});const ids=Array.isArray(b.memberIds)?b.memberIds.map(Number).filter(x=>x&&x!==u.id):[];for(const id of [...new Set(ids)])if(db.users.some(x=>x.id===id&&x.status==='active'))db.groupMembers.push({groupId:g.id,userId:id,role:'member'});save();return send(res,200,{group:{...g,ownerName:u.name}})}
 const gm=p.match(/^\/api\/groups\/([0-9]+(?:\.[0-9]+)?)$/);if(gm){const u=auth(req,res);if(!u)return;const gid=Number(gm[1]),g=db.groups.find(x=>x.id===gid),membership=db.groupMembers.find(m=>m.groupId===gid&&m.userId===u.id);if(!g)return send(res,404,{error:'Gruppe nicht gefunden.'});if(!membership&&u.role!=='admin')return send(res,403,{error:'Du bist kein Mitglied dieser Gruppe.'});if(req.method==='GET'){const members=db.groupMembers.filter(m=>m.groupId===gid).map(m=>{const x=db.users.find(u=>u.id===m.userId);return x?{...pub(x),groupRole:m.role}:null}).filter(Boolean);const messages=db.messages.filter(m=>m.chatType==='group'&&m.chatId===gid).slice(-500).map(messagePublic);const files=db.groupFiles.filter(f=>f.groupId===gid).map(groupFilePublic);const events=db.groupEvents.filter(e=>e.groupId===gid).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)).map(groupEventPublic);return send(res,200,{group:{...g,closed:!!g.closed,ownerName:db.users.find(x=>x.id===g.ownerId)?.name||'Unbekannt'},members,messages,files,events,typing:typingUsers('group',gid,u.id)})}if(req.method==='POST'){
  if(g.closed&&g.ownerId!==u.id&&u.role!=='admin')return send(res,403,{error:'Diese Gruppe ist geschlossen.'});
  const b=await parse(req),r=await createChatMessage(u,'group',gid,b);
  if(r.error)return send(res,400,{error:r.error});
  pushToChatRecipients(u.id,'group',gid,g.name,r.message.text||'📎 Neuer Anhang').catch(()=>{});
  return send(res,200,{ok:true,message:messagePublic(r.message)});
}if(req.method==='DELETE'){if(g.ownerId!==u.id&&u.role!=='admin')return send(res,403,{error:'Nur Gruppenbesitzer oder Admin darf die Gruppe löschen.'});db.messages=db.messages.filter(m=>!(m.chatType==='group'&&m.chatId===gid));db.groupMembers=db.groupMembers.filter(m=>m.groupId!==gid);for(const f of db.groupFiles.filter(f=>f.groupId===gid)) await deleteStorage(f.storageKey||f.stored);db.groupFiles=db.groupFiles.filter(f=>f.groupId!==gid);db.groupEvents=db.groupEvents.filter(e=>e.groupId!==gid);db.groups=db.groups.filter(x=>x.id!==gid);save();return send(res,200,{ok:true})}}
 const gr=p.match(/^\/api\/groups\/([0-9]+(?:\.[0-9]+)?)\/settings$/);if(gr&&req.method==='PATCH'){const u=auth(req,res);if(!u)return;const gid=Number(gr[1]),g=db.groups.find(x=>x.id===gid),membership=db.groupMembers.find(m=>m.groupId===gid&&m.userId===u.id);if(!g)return send(res,404,{error:'Gruppe nicht gefunden.'});if(!membership&&u.role!=='admin')return send(res,403,{error:'Kein Zugriff.'});const b=await parse(req);const isOwner=g.ownerId===u.id||u.role==='admin';if(!isOwner&&membership?.role!=='admin')return send(res,403,{error:'Keine Berechtigung.'});if(b.name!==undefined){const name=String(b.name).trim();if(name.length<2||name.length>60)return send(res,400,{error:'Gruppenname muss 2–60 Zeichen lang sein.'});g.name=name}if(Array.isArray(b.addMemberIds)){for(const uid of [...new Set(b.addMemberIds.map(Number))])if(uid&&db.users.some(x=>x.id===uid&&x.status==='active')&&!db.groupMembers.some(m=>m.groupId===gid&&m.userId===uid))db.groupMembers.push({groupId:gid,userId:uid,role:'member'})}if(Array.isArray(b.removeMemberIds)){for(const uid of [...new Set(b.removeMemberIds.map(Number))])if(uid!==g.ownerId)db.groupMembers=db.groupMembers.filter(m=>!(m.groupId===gid&&m.userId===uid))}if(Array.isArray(b.adminMemberIds)&&isOwner){for(const m of db.groupMembers.filter(m=>m.groupId===gid)){if(m.userId===g.ownerId)m.role='owner';else if(b.adminMemberIds.map(Number).includes(m.userId))m.role='admin';else m.role='member'}}save();return send(res,200,{ok:true,group:{...g}})}
 const gs=p.match(/^\/api\/groups\/([0-9]+(?:\.[0-9]+)?)\/status$/);if(gs&&req.method==='PATCH'){const u=auth(req,res);if(!u)return;const gid=Number(gs[1]),g=db.groups.find(x=>x.id===gid);if(!g)return send(res,404,{error:'Gruppe nicht gefunden.'});if(g.ownerId!==u.id&&u.role!=='admin')return send(res,403,{error:'Nur Besitzer oder Admin darf die Gruppe schließen.'});const b=await parse(req);g.closed=!!b.closed;save();return send(res,200,{ok:true,closed:g.closed})}
 const gf=p.match(/^\/api\/groups\/([0-9]+(?:\.[0-9]+)?)\/files$/);if(gf){const u=auth(req,res);if(!u)return;const gid=Number(gf[1]),g=db.groups.find(x=>x.id===gid);if(!g||(!groupMember(u,gid)&&u.role!=='admin'))return send(res,403,{error:'Kein Zugriff.'});if(req.method==='GET')return send(res,200,{files:db.groupFiles.filter(f=>f.groupId===gid).map(groupFilePublic)});if(req.method==='POST'){const b=await parse(req),name=String(b.name||'').trim(),data=String(b.data||''),approvalCode=String(b.approvalCode||'').trim();if(!name||!data.includes(','))return send(res,400,{error:'Datei fehlt.'});const raw=Buffer.from(data.split(',')[1],'base64');if(raw.length>50*1024*1024)return send(res,400,{error:'Maximal 50 MB.'});if(raw.length>10*1024*1024&&u.role!=='admin'){const code=db.uploadCodes.find(x=>x.code===approvalCode&&!x.usedAt&&x.expiresAt>Date.now());if(!code)return send(res,403,{error:'Für Dateien über 10 MB wird ein gültiger Admin-Freigabecode benötigt.'});code.usedAt=new Date().toISOString();code.usedBy=u.id;save()}const ext=path.extname(name).slice(0,12).replace(/[^a-zA-Z0-9.]/g,'');const stored=crypto.randomBytes(16).toString('hex')+ext;const storageKey=storagePath('groups',gid,stored);await uploadToStorage(raw,storageKey,String(b.mime||'application/octet-stream').slice(0,100));const f={id:Date.now()+Math.random(),groupId:gid,name:name.replace(/[\\/]/g,'_'),size:raw.length,mime:String(b.mime||'application/octet-stream').slice(0,100),ownerId:u.id,stored,storageKey,createdAt:new Date().toISOString()};db.groupFiles.push(f);save();return send(res,200,{file:groupFilePublic(f)})}}
 const gev=p.match(/^\/api\/groups\/([0-9]+(?:\.[0-9]+)?)\/events(?:\/([0-9]+(?:\.[0-9]+)?))?$/);if(gev){const u=auth(req,res);if(!u)return;const gid=Number(gev[1]),eid=gev[2]?Number(gev[2]):null,g=db.groups.find(x=>x.id===gid);if(!g||(!groupMember(u,gid)&&u.role!=='admin'))return send(res,403,{error:'Kein Zugriff.'});if(req.method==='GET')return send(res,200,{events:db.groupEvents.filter(e=>e.groupId===gid).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)).map(groupEventPublic)});if(req.method==='POST'){const b=await parse(req),title=String(b.title||'').trim(),date=String(b.date||''),time=String(b.time||'');if(!title||!/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/.test(date)||!/^[0-9]{2}:[0-9]{2}$/.test(time))return send(res,400,{error:'Titel, Datum und Uhrzeit erforderlich.'});const e={id:Date.now()+Math.random(),groupId:gid,title,date,time,description:String(b.description||'').slice(0,1000),creatorId:u.id,createdAt:new Date().toISOString()};db.groupEvents.push(e);save();return send(res,200,{event:groupEventPublic(e)})}if(req.method==='DELETE'&&eid){const e=db.groupEvents.find(x=>x.id===eid&&x.groupId===gid);if(!e)return send(res,404,{error:'Termin nicht gefunden.'});if(e.creatorId!==u.id&&g.ownerId!==u.id&&u.role!=='admin')return send(res,403,{error:'Keine Berechtigung.'});db.groupEvents=db.groupEvents.filter(x=>x.id!==eid);save();return send(res,200,{ok:true})}}
  const gfdDelete=p.match(/^\/api\/groups\/([0-9]+(?:\.[0-9]+)?)\/files\/([0-9]+(?:\.[0-9]+)?)$/);if(gfdDelete&&req.method==='DELETE'){const u=auth(req,res);if(!u)return;const gid=Number(gfdDelete[1]),fid=Number(gfdDelete[2]),g=db.groups.find(x=>x.id===gid),f=db.groupFiles.find(x=>x.id===fid&&x.groupId===gid);if(!g||!f)return send(res,404,{error:'Datei nicht gefunden.'});if(f.ownerId!==u.id&&g.ownerId!==u.id&&u.role!=='admin')return send(res,403,{error:'Nur Besitzer, Gruppenbesitzer oder Admin darf löschen.'});try{await deleteStorage(f.storageKey||f.stored)}catch{}db.groupFiles=db.groupFiles.filter(x=>x.id!==f.id);save();return send(res,200,{ok:true})}
const gfd=p.match(/^\/api\/groups\/([0-9]+(?:\.[0-9]+)?)\/files\/([0-9]+(?:\.[0-9]+)?)\/download$/);if(gfd&&req.method==='GET'){const u=auth(req,res);if(!u)return;const gid=Number(gfd[1]),fid=Number(gfd[2]),f=db.groupFiles.find(x=>x.id===fid&&x.groupId===gid);if(!f||(!groupMember(u,gid)&&u.role!=='admin'))return send(res,403,{error:'Keine Berechtigung.'});try{return send(res,200,{url:await signedDownload(f.storageKey||f.stored)})}catch(e){return send(res,404,{error:'Datei fehlt in Supabase Storage.'})}}
 const gmp=p.match(/^\/api\/groups\/([0-9]+(?:\.[0-9]+)?)\/members\/([0-9]+(?:\.[0-9]+)?)$/);if(gmp){const u=auth(req,res);if(!u)return;const gid=Number(gmp[1]),uid=Number(gmp[2]),g=db.groups.find(x=>x.id===gid),own=g&&g.ownerId===u.id;if(!g)return send(res,404,{error:'Gruppe nicht gefunden.'});if(!own&&u.role!=='admin')return send(res,403,{error:'Nur Gruppenbesitzer oder Admin darf Mitglieder verwalten.'});if(!db.users.some(x=>x.id===uid&&x.status==='active'))return send(res,404,{error:'Benutzer nicht gefunden.'});if(req.method==='POST'){if(!db.groupMembers.some(m=>m.groupId===gid&&m.userId===uid))db.groupMembers.push({groupId:gid,userId:uid,role:'member'});save();return send(res,200,{ok:true})}if(req.method==='DELETE'){if(uid===g.ownerId)return send(res,400,{error:'Der Besitzer kann nicht entfernt werden.'});db.groupMembers=db.groupMembers.filter(m=>!(m.groupId===gid&&m.userId===uid));save();return send(res,200,{ok:true})}}
 if(req.method==='GET'&&p==='/api/groups/users'){const u=auth(req,res);if(!u)return;return send(res,200,{users:db.users.filter(x=>x.id!==u.id&&x.status==='active').map(pub)})}
  const chatMedia=p.match(/^\/api\/chat\/media\/([0-9]+(?:\.[0-9]+)?)$/);
 if(chatMedia&&req.method==='GET'){
   const u=auth(req,res);if(!u)return;
   const mid=Number(chatMedia[1]),m=db.messages.find(x=>x.id===mid),a=m?.attachment;
   if(!m||!a?.storageKey)return send(res,404,{error:'Anhang nicht gefunden.'});
   let allowed=false;
   if(m.chatType==='class')allowed=member(u.id,m.chatId)||u.role==='admin';
   else if(m.chatType==='group')allowed=groupMember(u,m.chatId)||u.role==='admin';
   else if(m.chatType==='private'){const c=db.chats.find(x=>x.id===m.chatId);allowed=!!c&&(c.userA===u.id||c.userB===u.id);}
   if(!allowed)return send(res,403,{error:'Kein Zugriff auf diesen Anhang.'});
   try{const signed=await signedDownload(a.storageKey);res.writeHead(302,{Location:signed,'Cache-Control':'private, max-age=30'});return res.end()}catch(e){return send(res,500,{error:'Anhang konnte nicht geladen werden.'})}
 }
 const rr=p.match(/^\/api\/messages\/([0-9]+(?:\.[0-9]+)?)\/reaction$/);if(rr&&req.method==='POST'){const u=auth(req,res);if(!u)return;const mid=Number(rr[1]),m=db.messages.find(x=>x.id===mid);if(!m)return send(res,404,{error:'Nachricht nicht gefunden.'});let allowed=false;if(m.chatType==='class')allowed=member(u.id,m.chatId)||u.role==='admin';else if(m.chatType==='group')allowed=groupMember(u,m.chatId)||u.role==='admin';else if(m.chatType==='private'){const c=db.chats.find(x=>x.id===m.chatId);allowed=!!c&&(c.userA===u.id||c.userB===u.id)&&privateAllowed(u,db.users.find(x=>x.id===(c.userA===u.id?c.userB:c.userA)));}if(!allowed)return send(res,403,{error:'Kein Zugriff.'});const b=await parse(req),emoji=String(b.emoji||'').trim();const allowedEmoji=['👍','❤️','😂','😮','😢','😡','🎉','👏','🔥','🚀'];if(!allowedEmoji.includes(emoji))return send(res,400,{error:'Ungültige Reaktion.'});m.reactions=Array.isArray(m.reactions)?m.reactions:[];const idx=m.reactions.findIndex(r=>r.userId===u.id&&r.emoji===emoji);if(idx>=0)m.reactions.splice(idx,1);else{m.reactions=m.reactions.filter(r=>r.userId!==u.id);m.reactions.push({userId:u.id,emoji});}save();return send(res,200,{ok:true,message:messagePublic(m)})}
 const md=p.match(/^\/api\/messages\/([0-9]+(?:\.[0-9]+)?)$/);if(md&&req.method==='DELETE'){const u=auth(req,res);if(!u)return;const m=db.messages.find(x=>x.id===Number(md[1]));if(!m)return send(res,200,{ok:true,alreadyDeleted:true});const allowed=m.userId===u.id||u.role==='admin';if(!allowed)return send(res,403,{error:'Du darfst nur deine eigenen Nachrichten löschen.'});if(m.attachment?.storageKey)await deleteStorage(m.attachment.storageKey);db.messages=db.messages.filter(x=>x.id!==m.id);save();return send(res,200,{ok:true})}
 // CLOUD: private files or files shared with an entire class
 if(req.method==='GET'&&p==='/api/cloud'){const u=auth(req,res);if(!u)return;const ownClassIds=db.memberships.filter(m=>m.userId===u.id).map(m=>m.classId);const files=db.files.filter(f=>f.ownerId===u.id||(f.scope==='class'&&ownClassIds.includes(f.classId))||(u.role==='admin'&&f.scope==='class')).map(filePublic).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));return send(res,200,{files,classes:db.classes.filter(c=>ownClassIds.includes(c.id))})}
 if(req.method==='POST'&&p==='/api/cloud'){const u=auth(req,res);if(!u)return;const b=await parse(req),name=String(b.name||'').trim(),scope=b.scope==='class'?'class':'private',classId=Number(b.classId||0),data=String(b.data||''),approvalCode=String(b.approvalCode||'').trim();if(!name||name.length>160)return send(res,400,{error:'Dateiname ungültig.'});if(!data||!data.includes(','))return send(res,400,{error:'Dateiinhalt fehlt.'});const raw=Buffer.from(data.split(',')[1],'base64');const TEN=10*1024*1024,MAX=50*1024*1024;if(raw.length>MAX)return send(res,400,{error:'Datei zu groß. Maximal 50 MB.'});if(raw.length>TEN&&u.role!=='admin'){const now=Date.now(),code=db.uploadCodes.find(x=>x.code===approvalCode&&!x.usedAt&&x.expiresAt>now);if(!code)return send(res,403,{error:'Diese Datei ist größer als 10 MB. Für den Upload wird ein gültiger Admin-Freigabecode benötigt.'});code.usedAt=new Date(now).toISOString();code.usedBy=u.id;save()}if(scope==='class'&&!member(u.id,classId)&&u.role!=='admin')return send(res,403,{error:'Du bist nicht Mitglied dieser Klasse.'});const ext=path.extname(name).slice(0,12).replace(/[^a-zA-Z0-9.]/g,'');const id=Date.now()+Math.random();const stored=crypto.randomBytes(16).toString('hex')+ext;const storageKey=storagePath(scope==='class'?'classes':'private',scope==='class'?classId:u.id,stored);try{await uploadToStorage(raw,storageKey,String(b.mime||'application/octet-stream').slice(0,100))}catch(e){return send(res,500,{error:'Datei konnte nicht gespeichert werden.'})}const f={id,name:name.replace(/[\/]/g,'_'),size:raw.length,mime:String(b.mime||'application/octet-stream').slice(0,100),scope,classId:scope==='class'?classId:null,ownerId:u.id,stored,storageKey,createdAt:new Date().toISOString()};db.files.push(f);save();return send(res,200,{file:filePublic(f)})}
 const fd=p.match(/^\/api\/cloud\/([0-9]+(?:\.[0-9]+)?)\/download$/);if(fd&&req.method==='GET'){const u=auth(req,res);if(!u)return;const f=db.files.find(x=>x.id===Number(fd[1]));if(!f)return send(res,404,{error:'Datei nicht gefunden'});const allowed=f.ownerId===u.id||(f.scope==='class'&&member(u.id,f.classId))||(u.role==='admin'&&f.scope==='class');if(!allowed)return send(res,403,{error:'Keine Berechtigung für diese Datei.'});try{return send(res,200,{url:await signedDownload(f.storageKey||f.stored)})}catch(e){return send(res,404,{error:'Datei fehlt in Supabase Storage.'})}}
 const fx=p.match(/^\/api\/cloud\/([0-9]+(?:\.[0-9]+)?)$/);if(fx&&req.method==='DELETE'){const u=auth(req,res);if(!u)return;const f=db.files.find(x=>x.id===Number(fx[1]));if(!f)return send(res,404,{error:'Datei nicht gefunden'});if(f.ownerId!==u.id&&u.role!=='admin')return send(res,403,{error:'Nur Besitzer oder Admin darf löschen.'});await deleteStorage(f.storageKey||f.stored);db.files=db.files.filter(x=>x.id!==f.id);save();return send(res,200,{ok:true})}
 // CLASS-WIDE CALENDAR: Homework, appointments, exams
 if(req.method==='GET'&&p==='/api/calendar'){const u=auth(req,res);if(!u)return;const classIds=db.memberships.filter(m=>m.userId===u.id).map(m=>m.classId);const classes=db.classes.filter(c=>classIds.includes(c.id));const events=db.events.filter(e=>classIds.includes(e.classId)).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)).map(eventPublic);return send(res,200,{events,classes})}
 if(req.method==='POST'&&p==='/api/calendar'){const u=auth(req,res);if(!u)return;const b=await parse(req),classId=Number(b.classId),type=['homework','appointment','exam'].includes(b.type)?b.type:'appointment',title=String(b.title||'').trim(),date=String(b.date||''),time=String(b.time||'');if(!teacherForClass(u.id,classId))return send(res,403,{error:'Nur Lehrer der Klasse oder Administratoren dürfen Hausaufgaben, Termine und Prüfungen erstellen.'});if(!title||!/^\d{4}-\d{2}-\d{2}$/.test(date)||!/^\d{2}:\d{2}$/.test(time))return send(res,400,{error:'Titel, Datum und Uhrzeit sind erforderlich.'});const e={id:Date.now()+Math.random(),classId,type,title,date,time,description:String(b.description||'').slice(0,1000),subject:String(b.subject||'').slice(0,80),createdBy:u.id,creatorId:u.id,createdAt:new Date().toISOString()};db.events.push(e);save();return send(res,200,{event:eventPublic(e)})}
 const ed=p.match(/^\/api\/calendar\/([0-9]+(?:\.[0-9]+)?)$/);if(ed&&req.method==='DELETE'){const u=auth(req,res);if(!u)return;const e=db.events.find(x=>x.id===Number(ed[1]));if(!e)return send(res,404,{error:'Termin nicht gefunden'});if(e.creatorId!==u.id&&u.role!=='admin')return send(res,403,{error:'Nur Ersteller oder Admin darf löschen.'});db.events=db.events.filter(x=>x.id!==e.id);save();return send(res,200,{ok:true})}
  if(req.method==='GET'&&p==='/api/announcements'){const u=auth(req,res);if(!u)return;const classIds=db.memberships.filter(m=>m.userId===u.id).map(m=>m.classId);const rows=(db.announcements||[]).filter(x=>x.active!==false&&(x.audience==='all'||x.audience===u.role||(x.audience==='class'&&classIds.includes(Number(x.classId))))).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt));return send(res,200,{announcements:rows})}
if(req.method==='POST'&&p==='/api/admin/announcements'){const a=admin(req,res);if(!a)return;const b=await parse(req),title=String(b.title||'').trim(),text=String(b.text||'').trim(),audience=['all','user','teacher','class'].includes(b.audience)?b.audience:'all',classId=audience==='class'?Number(b.classId):null;if(!title||!text)return send(res,400,{error:'Titel und Nachricht sind erforderlich.'});if(audience==='class'&&!db.classes.some(c=>c.id===classId))return send(res,400,{error:'Klasse nicht gefunden.'});const x={id:Date.now()+Math.random(),title,text,audience,classId,active:true,creatorId:a.id,createdAt:new Date().toISOString()};db.announcements=db.announcements||[];db.announcements.push(x);audit(a.id,'GLOBAL_ANNOUNCEMENT_CREATE',title);save();return send(res,200,{announcement:x})}
if(req.method==='DELETE'&&p.startsWith('/api/admin/announcements/')){const a=admin(req,res);if(!a)return;const id=Number(p.split('/').pop()),before=(db.announcements||[]).length;db.announcements=(db.announcements||[]).filter(x=>x.id!==id);if(db.announcements.length===before)return send(res,404,{error:'Ankündigung nicht gefunden.'});audit(a.id,'ANNOUNCEMENT_DELETE',String(id));save();return send(res,200,{ok:true})}
if(req.method==='GET'&&p==='/api/timetable'){
 const u=auth(req,res);if(!u)return;const ids=db.memberships.filter(m=>m.userId===u.id).map(m=>m.classId);const classes=db.classes.filter(c=>ids.includes(c.id)||u.role==='admin');
 return send(res,200,{classes,settings:db.timetableSettings,timetable:db.timetable.filter(t=>ids.includes(t.classId)||u.role==='admin').sort((a,b)=>(a.day-b.day)||(a.period-b.period))})
}
 if(req.method==='POST'&&p==='/api/admin/timetable'){
  const a=admin(req,res);if(!a)return;
  const b=await parse(req),classId=Number(b.classId),day=Number(b.day),period=Number(b.period),subject=String(b.subject||'').trim(),teacher=String(b.teacher||'').trim(),room=String(b.room||'').trim(),startTime=String(b.startTime||'').trim(),endTime=String(b.endTime||'').trim();
  if(!db.classes.some(c=>c.id===classId)||day<1||day>5||period<1||period>20||!subject||!/^\d{2}:\d{2}$/.test(startTime)||!/^\d{2}:\d{2}$/.test(endTime))return send(res,400,{error:'Klasse, Tag, Stunde, Fach, Startzeit und Endzeit sind erforderlich.'});
  const existing=db.timetable.find(t=>t.classId===classId&&t.day===day&&t.period===period);
  if(existing)Object.assign(existing,{subject,teacher,room,startTime,endTime});else db.timetable.push({id:Date.now()+Math.random(),classId,day,period,subject,teacher,room,startTime,endTime});
  audit(a.id,'TIMETABLE_SAVE',`Klasse ${classId}, Tag ${day}, Stunde ${period}`);save();return send(res,200,{ok:true})
}
const at=p.match(/^\/api\/admin\/timetable\/(.+)$/);if(at&&(req.method==='DELETE'||req.method==='PATCH')){
  const a=admin(req,res);if(!a)return;const id=Number(at[1]);const row=db.timetable.find(x=>x.id===id);
  if(!row)return send(res,404,{error:'Stunde nicht gefunden.'});
  if(req.method==='DELETE'){db.timetable=db.timetable.filter(x=>x.id!==id);audit(a.id,'TIMETABLE_DELETE',`Stunde ${id}`);save();return send(res,200,{ok:true})}
  const b=await parse(req);const day=Number(b.day)||row.day,period=Number(b.period)||row.period,subject=String(b.subject??row.subject).trim(),teacher=String(b.teacher??row.teacher).trim(),room=String(b.room??row.room).trim(),startTime=String(b.startTime??row.startTime).trim(),endTime=String(b.endTime??row.endTime).trim();
  if(day<1||day>5||period<1||period>20||!subject)return send(res,400,{error:'Ungültige Stundenplandaten.'});
  Object.assign(row,{day,period,subject,teacher,room});audit(a.id,'TIMETABLE_UPDATE',`Stunde ${id}`);save();return send(res,200,{ok:true})
}
if(req.method==='POST'&&p==='/api/admin/timetable/settings'){
  const a=admin(req,res);if(!a)return;const b=await parse(req),classId=Number(b.classId),day=Number(b.day);
  if(!db.classes.some(c=>c.id===classId)||day<1||day>5)return send(res,400,{error:'Klasse und Wochentag sind erforderlich.'});
  const startTime=/^\d{2}:\d{2}$/.test(String(b.startTime||''))?String(b.startTime):'08:00';
  const lessonMinutes=Math.max(1,Math.min(180,Number(b.lessonMinutes)||45));
  const breakMinutes=Math.max(0,Math.min(120,Number(b.breakMinutes)||15));
  let st=db.timetableSettings.find(x=>x.classId===classId&&x.day===day);
  if(!st){st={classId,day,startTime,lessonMinutes,breakMinutes};db.timetableSettings.push(st)}else Object.assign(st,{startTime,lessonMinutes,breakMinutes});
  audit(a.id,'TIMETABLE_SETTINGS',`Klasse ${classId}, Tag ${day}`);save();return send(res,200,{ok:true,settings:st})
}

if(req.method==='GET'&&p==='/api/admin/upload-codes'){const a=admin(req,res);if(!a)return;const now=Date.now();db.uploadCodes=db.uploadCodes.filter(x=>x.expiresAt>now&&!x.usedAt);return send(res,200,{codes:db.uploadCodes.map(x=>({code:x.code,createdAt:x.createdAt,expiresAt:x.expiresAt,usedAt:x.usedAt||null}))})}
 if(req.method==='POST'&&p==='/api/admin/upload-codes'){const a=admin(req,res);if(!a)return;const code=crypto.randomBytes(6).toString('hex').toUpperCase();const created=Date.now();db.uploadCodes.push({code,createdAt:new Date(created).toISOString(),expiresAt:created+30*60*1000,usedAt:null,createdBy:a.id});audit(a.id,'UPLOAD_CODE_CREATE','30-Minuten-Code '+code);save();return send(res,200,{code,expiresAt:created+30*60*1000})}
 if(req.method==='GET'&&p==='/api/admin/private-blocks'){
  const a=admin(req,res);if(!a)return;
  return send(res,200,{blocks:db.privateBlocks.map(x=>({...x,userA:pub(db.users.find(u=>u.id===x.userA)),userB:pub(db.users.find(u=>u.id===x.userB))})).filter(x=>x.userA&&x.userB)});
 }
 if(req.method==='POST'&&p==='/api/admin/private-blocks'){
  const a=admin(req,res);if(!a)return;const b=await parse(req),userA=Number(b.userA),userB=Number(b.userB);
  if(!userA||!userB||userA===userB)return send(res,400,{error:'Bitte zwei unterschiedliche Benutzer auswählen.'});
  if(!db.users.some(x=>x.id===userA&&x.status==='active')||!db.users.some(x=>x.id===userB&&x.status==='active'))return send(res,400,{error:'Benutzer nicht gefunden oder nicht aktiv.'});
  if(!privateBlocked({id:userA},{id:userB})){db.privateBlocks.push({id:Date.now()+Math.random(),userA,userB,createdAt:new Date().toISOString(),createdBy:a.id});audit(a.id,'PRIVATE_CHAT_BLOCK',`Privatchat zwischen ${db.users.find(x=>x.id===userA)?.name||userA} und ${db.users.find(x=>x.id===userB)?.name||userB} gesperrt`);save();}
  return send(res,200,{ok:true});
 }
 const pb=p.match(/^\/api\/admin\/private-blocks\/([0-9]+(?:\.[0-9]+)?)$/);
 if(pb&&req.method==='DELETE'){
  const a=admin(req,res);if(!a)return;const id=Number(pb[1]);db.privateBlocks=db.privateBlocks.filter(x=>x.id!==id);audit(a.id,'PRIVATE_CHAT_UNBLOCK','Privatchat-Sperre aufgehoben');save();return send(res,200,{ok:true});
 }
 if(req.method==='GET'&&p==='/api/admin/users'){const a=admin(req,res);if(!a)return;return send(res,200,{users:db.users.map(pub)})}
 if(req.method==='GET'&&p==='/api/admin/stats'){const a=admin(req,res);if(!a)return;return send(res,200,{users:db.users.length,active:db.users.filter(x=>x.status==='active').length,banned:db.users.filter(x=>x.status==='banned').length,admins:db.users.filter(x=>x.role==='admin').length,teachers:db.users.filter(x=>x.role==='teacher').length,classes:db.classes.length,classMembers:db.memberships.length,messages:db.messages.length,groups:db.groups.length,groupMembers:db.groupMembers.length,files:db.files.length,events:db.events.length})}
 if(req.method==='GET'&&p==='/api/admin/audit'){const a=admin(req,res);if(!a)return;return send(res,200,{logs:db.audit.map(x=>({...x,adminName:db.users.find(u=>u.id===x.adminId)?.name||'Unbekannt'}))})}
 if(req.method==='GET'&&p==='/api/admin/classes'){const a=admin(req,res);if(!a)return;return send(res,200,{classes:db.classes.map(c=>({...c,members:db.memberships.filter(m=>m.classId===c.id).map(m=>{const u=db.users.find(x=>x.id===m.userId);return u?pub(u):null}).filter(Boolean)}))})}
 const ac=p.match(/^\/api\/admin\/classes\/([0-9]+(?:\.[0-9]+)?)\/members\/([0-9]+(?:\.[0-9]+)?)$/);if(ac){const a=admin(req,res);if(!a)return;const cid=Number(ac[1]),uid=Number(ac[2]);if(!db.classes.some(c=>c.id===cid)||!db.users.some(u=>u.id===uid))return send(res,404,{error:'Nicht gefunden'});if(req.method==='POST'){if(!member(uid,cid)){const target=db.users.find(x=>x.id===uid);db.memberships.push({userId:uid,classId:cid,role:target?.role==='teacher'?'teacher':'member'});audit(a.id,'CLASS_ADD_MEMBER',`User ${uid} -> Klasse ${cid}`);save()}return send(res,200,{ok:true})}if(req.method==='DELETE'){db.memberships=db.memberships.filter(m=>!(m.userId===uid&&m.classId===cid));audit(a.id,'CLASS_REMOVE_MEMBER',`User ${uid} aus Klasse ${cid}`);save();return send(res,200,{ok:true})}}
 if(req.method==='POST'&&p==='/api/admin/classes'){const a=admin(req,res),b=await parse(req);if(!a)return;if(!String(b.name||'').trim())return send(res,400,{error:'Klassenname fehlt.'});const name=String(b.name).trim();if(db.classes.some(c=>c.name.toLowerCase()===name.toLowerCase()))return send(res,400,{error:'Klasse existiert bereits.'});const c={id:Date.now(),name,ownerId:a.id,createdAt:new Date().toISOString()};db.classes.push(c);db.memberships.push({userId:a.id,classId:c.id,role:'admin'});audit(a.id,'CLASS_CREATE',name);save();return send(res,200,{class:c})}
 const acl=p.match(/^\/api\/admin\/classes\/([0-9]+(?:\.[0-9]+)?)$/);if(acl&&(req.method==='DELETE'||req.method==='PATCH')){
  const a=admin(req,res);if(!a)return;const cid=Number(acl[1]),cl=db.classes.find(c=>c.id===cid);if(!cl)return send(res,404,{error:'Klasse nicht gefunden.'});
  if(req.method==='PATCH'){const b=await parse(req),name=String(b.name||'').trim();if(name.length<1||name.length>40)return send(res,400,{error:'Klassenname ungültig.'});if(db.classes.some(x=>x.id!==cid&&x.name.toLowerCase()===name.toLowerCase()))return send(res,400,{error:'Klasse existiert bereits.'});cl.name=name;audit(a.id,'CLASS_RENAME',`Klasse ${cid} -> ${name}`);save();return send(res,200,{class:cl})}
  db.classes=db.classes.filter(x=>x.id!==cid);db.memberships=db.memberships.filter(m=>m.classId!==cid);db.timetable=db.timetable.filter(t=>t.classId!==cid);db.timetableSettings=db.timetableSettings.filter(t=>t.classId!==cid);
  for(const f of db.files.filter(f=>f.scope==='class'&&f.classId===cid))await deleteStorage(f.storageKey||f.stored);
  db.files=db.files.filter(f=>!(f.scope==='class'&&f.classId===cid));db.events=db.events.filter(e=>e.classId!==cid);db.messages=db.messages.filter(m=>!(m.chatType==='class'&&m.chatId===cid));
  audit(a.id,'CLASS_DELETE',`Klasse ${cid} (${cl.name})`);save();return send(res,200,{ok:true})
}
 const ar=p.match(/^\/api\/admin\/users\/([0-9]+(?:\.[0-9]+)?)\/reset-password$/);if(ar&&req.method==='POST'){const a=admin(req,res);if(!a)return;const id=Number(ar[1]),u=db.users.find(x=>x.id===id);if(!u)return send(res,404,{error:'Benutzer nicht gefunden'});const b=await parse(req);const pw=String(b.password||'');if(pw.length<8)return send(res,400,{error:'Das neue Passwort muss mindestens 8 Zeichen haben.'});const h=hash(pw);u.passwordHash=h.hash;u.passwordSalt=h.salt;db.sessions=db.sessions.filter(s=>s.userId!==id);audit(a.id,'PASSWORD_RESET',`Passwort von User ${id} zurückgesetzt`);save();return send(res,200,{ok:true})}
 const au=p.match(/^\/api\/admin\/users\/([0-9]+(?:\.[0-9]+)?)$/);if(au){const a=admin(req,res);if(!a)return;const id=Number(au[1]),u=db.users.find(x=>x.id===id);if(!u)return send(res,404,{error:'Benutzer nicht gefunden'});if(req.method==='PATCH'){const b=await parse(req);if(id===a.id&&b.status==='banned')return send(res,400,{error:'Du kannst dich nicht selbst sperren.'});if(b.role&&['user','teacher','admin'].includes(b.role)){u.role=b.role;db.memberships.forEach(m=>{if(m.userId===u.id&&m.role!=='admin')m.role=b.role==='teacher'?'teacher':'member'})}if(b.status&&['active','banned'].includes(b.status))u.status=b.status;u.moderation=u.moderation||{};for(const k of ['nameHidden','bioHidden','avatarHidden'])if(typeof b[k]==='boolean')u.moderation[k]=b[k];audit(a.id,'USER_UPDATE',`User ${id}`);save();return send(res,200,{ok:true,user:pub(u)})}if(req.method==='DELETE'){if(id===a.id)return send(res,400,{error:'Du kannst dich nicht selbst löschen.'});db.users=db.users.filter(x=>x.id!==id);db.memberships=db.memberships.filter(m=>m.userId!==id);db.chats=db.chats.filter(c=>c.userA!==id&&c.userB!==id);db.groupMembers=db.groupMembers.filter(m=>m.userId!==id);db.groups=db.groups.filter(g=>g.ownerId!==id);for(const f of db.groupFiles.filter(f=>f.ownerId===id)) await deleteStorage(f.storageKey||f.stored);db.groupFiles=db.groupFiles.filter(f=>f.ownerId!==id);db.groupEvents=db.groupEvents.filter(e=>e.creatorId!==id);db.messages=db.messages.filter(m=>m.userId!==id);for(const f of db.files.filter(f=>f.ownerId===id)) await deleteStorage(f.storageKey||f.stored);db.files=db.files.filter(f=>f.ownerId!==id);db.events=db.events.filter(e=>e.creatorId!==id);audit(a.id,'USER_DELETE',`User ${id}`);save();return send(res,200,{ok:true})}}
 send(res,404,{error:'Nicht gefunden'})
}
function loginResponse(res,u){u.lastSeen=Date.now();const sid=crypto.randomBytes(32).toString('hex');sessions.set(sid,u.id);db.sessions=db.sessions.filter(x=>x.userId!==u.id||x.expiresAt<=Date.now());db.sessions.push({sid,userId:u.id,expiresAt:Date.now()+604800000,createdAt:new Date().toISOString()});save();return send(res,200,{ok:true,user:pub(u)},{'Set-Cookie':`sid=${sid}; HttpOnly; SameSite=Lax; Path=/; Max-Age=604800`})}
const server=http.createServer(async(req,res)=>{try{const p=url.parse(req.url).pathname;if(p.startsWith('/api/'))return await api(req,res,p);let file=path.normalize(path.join(ROOT,p==='/'?'index.html':p));if(!file.startsWith(ROOT))return send(res,403,'Forbidden');if(!fs.existsSync(file)||fs.statSync(file).isDirectory())file=path.join(ROOT,'index.html');res.writeHead(200,{'Content-Type':mime[path.extname(file)]||'application/octet-stream'});fs.createReadStream(file).pipe(res)}catch(e){console.error(e);send(res,500,{error:'Serverfehler'})}});
const port=Number(process.env.PORT||3000);server.on('error',e=>{console.error(e);process.exit(1)});(async()=>{try{await loadDB();let changed=seed();changed=seedTimetable()||changed;if(changed)await persist();await ensureBucket();server.listen(port,'0.0.0.0',()=>console.log(`KlassenCloud läuft auf Port ${port}`))}catch(e){console.error('Start fehlgeschlagen:',e);process.exit(1)}})();
