const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto'),url=require('url');
const { createClient } = require('@supabase/supabase-js');
const ROOT=__dirname;
const SUPABASE_URL=process.env.SUPABASE_URL;
const SUPABASE_SERVICE_ROLE_KEY=process.env.SUPABASE_SERVICE_ROLE_KEY;
const SUPABASE_BUCKET=process.env.SUPABASE_BUCKET||'klassencloud-files';
if(!SUPABASE_URL||!SUPABASE_SERVICE_ROLE_KEY){console.error('Fehlende Umgebungsvariablen: SUPABASE_URL und SUPABASE_SERVICE_ROLE_KEY');process.exit(1)}
const supabase=createClient(SUPABASE_URL,SUPABASE_SERVICE_ROLE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8'};
const empty={users:[],classes:[],memberships:[],chats:[],messages:[],groups:[],groupMembers:[],audit:[],files:[],events:[],groupFiles:[],groupEvents:[],timetable:[],timetableSettings:[],sessions:[]};
let db=structuredClone(empty);
let persistTimer=null,persistRunning=false,persistAgain=false;
async function loadDB(){const {data,error}=await supabase.from('app_state').select('state').eq('id',1).maybeSingle();if(error)throw error;if(data?.state){db={...structuredClone(empty),...data.state};for(const k of Object.keys(empty))if(!Array.isArray(db[k]))db[k]=[]}else await persist();}
async function persist(){if(persistRunning){persistAgain=true;return}persistRunning=true;try{const {error}=await supabase.from('app_state').upsert({id:1,state:db,updated_at:new Date().toISOString()},{onConflict:'id'});if(error)throw error}catch(e){console.error('Supabase-Speicherung fehlgeschlagen:',e.message)}finally{persistRunning=false;if(persistAgain){persistAgain=false;persist()}}}
function save(){clearTimeout(persistTimer);persistTimer=setTimeout(()=>persist(),80)}
async function ensureBucket(){const {data}=await supabase.storage.listBuckets();if(!data?.some(b=>b.name===SUPABASE_BUCKET)){const {error}=await supabase.storage.createBucket(SUPABASE_BUCKET,{public:false,fileSizeLimit:8*1024*1024});if(error&&!/already exists/i.test(error.message))throw error}}
function hash(password,salt=crypto.randomBytes(16).toString('hex')){return {salt,hash:crypto.scryptSync(password,salt,64).toString('hex')}}
function seed(){if(db.users.length)return false;const h=hash('Admin123!');const admin={id:1,name:'Administrator',passwordHash:h.hash,passwordSalt:h.salt,role:'admin',status:'active',lastSeen:Date.now(),createdAt:new Date().toISOString()};db.users.push(admin);db.classes.push({id:1,name:'8A',ownerId:1,createdAt:new Date().toISOString()});db.classes.push({id:2,name:'10B',ownerId:1,createdAt:new Date().toISOString()});db.memberships.push({userId:1,classId:1,role:'admin'});db.groups.push({id:1,name:'8A – Klassengruppe',ownerId:1,createdAt:new Date().toISOString()});db.groupMembers.push({groupId:1,userId:1,role:'owner'});return true}
function seedTimetable(){if(db.timetableSettings.length||!db.classes.some(c=>c.name==='8A'))return false;const c=db.classes.find(c=>c.name==='8A');db.timetableSettings.push({classId:c.id,lessonMinutes:45,breakMinutes:15});const days={1:[['Mathematik','Herr Müller','204'],['Deutsch','Frau Weber','201'],['Englisch','Herr Klein','203'],['Biologie','Frau Lang','105'],['Sport','Herr Bauer','Turnhalle'],['Geschichte','Frau Roth','202']],2:[['Deutsch','Frau Weber','201'],['Mathematik','Herr Müller','204'],['Physik','Herr Sommer','106'],['Kunst','Frau König','107'],['Englisch','Herr Klein','203'],['Musik','Frau Wolf','Aula']],3:[['Englisch','Herr Klein','203'],['Mathematik','Herr Müller','204'],['Geschichte','Frau Roth','202'],['Deutsch','Frau Weber','201'],['Informatik','Herr Maier','PC1'],['Sport','Herr Bauer','Turnhalle']],4:[['Mathematik','Herr Müller','204'],['Biologie','Frau Lang','105'],['Deutsch','Frau Weber','201'],['Geografie','Frau Roth','202'],['Englisch','Herr Klein','203'],['Kunst','Frau König','107']],5:[['Deutsch','Frau Weber','201'],['Mathematik','Herr Müller','204'],['Chemie','Herr Sommer','106'],['Geschichte','Frau Roth','202'],['Sport','Herr Bauer','Turnhalle'],['Klassenstunde','Frau Weber','201']]};for(const [day,lessons] of Object.entries(days))lessons.forEach((x,i)=>db.timetable.push({id:Date.now()+Math.random(),classId:c.id,day:Number(day),period:i+1,subject:x[0],teacher:x[1],room:x[2]}));return true}
const sessions=new Map(),typingState=new Map();
const nowMs=()=>Date.now();
function isOnline(u){return !!u&&!!u.lastSeen&&nowMs()-u.lastSeen<120000}
function send(res,status,data,headers={}){res.writeHead(status,{'Content-Type':typeof data==='string'?'text/plain; charset=utf-8':'application/json; charset=utf-8','Cache-Control':'no-store',...headers});res.end(typeof data==='string'?data:JSON.stringify(data))}
function cookies(req){return Object.fromEntries((req.headers.cookie||'').split(';').filter(Boolean).map(x=>{const i=x.indexOf('=');return [x.slice(0,i).trim(),decodeURIComponent(x.slice(i+1))]}))}
function me(req){const sid=cookies(req).sid,rec=db.sessions.find(x=>x.sid===sid&&x.expiresAt>Date.now()),u=rec&&db.users.find(u=>u.id===rec.userId&&u.status==='active');if(u){u.lastSeen=nowMs();}return u}
function pub(u){return {id:u.id,name:u.name,role:u.role,status:u.status,online:isOnline(u),lastSeen:u.lastSeen||null,createdAt:u.createdAt}}
function parse(req){return new Promise((resolve,reject)=>{let b='';req.on('data',c=>{b+=c;if(b.length>12e6){req.destroy();reject(new Error('Payload zu groß'))}});req.on('end',()=>{try{resolve(b?JSON.parse(b):{})}catch{resolve({})}});req.on('error',reject)})}
function auth(req,res){const u=me(req);if(!u){send(res,401,{error:'Nicht eingeloggt'});return null}return u}
function admin(req,res){const u=auth(req,res);if(!u)return null;if(u.role!=='admin'){send(res,403,{error:'Nur Administratoren dürfen das.'});return null}return u}
function member(userId,classId){return db.memberships.some(m=>m.userId===userId&&m.classId===classId)}
function audit(uid,action,detail){db.audit.unshift({id:Date.now()+Math.random(),adminId:uid,action,detail,createdAt:new Date().toISOString()});db.audit=db.audit.slice(0,500)}
function privateAllowed(a,b){return a&&b&&a.id!==b.id&&a.status==='active'&&b.status==='active'}
function chatForUsers(a,b){let c=db.chats.find(x=>x.type==='private'&&((x.userA===a&&x.userB===b)||(x.userA===b&&x.userB===a)));if(!c){c={id:Date.now()+Math.random(),type:'private',userA:a,userB:b,createdAt:new Date().toISOString()};db.chats.push(c);save()}return c}
function messagePublic(m){const u=db.users.find(x=>x.id===m.userId);return {id:m.id,userId:m.userId,userName:u?.name||'Unbekannt',text:m.text,createdAt:m.createdAt}}
function filePublic(f){return {id:f.id,name:f.name,size:f.size,mime:f.mime,scope:f.scope,classId:f.classId||null,ownerId:f.ownerId,ownerName:db.users.find(u=>u.id===f.ownerId)?.name||'Unbekannt',createdAt:f.createdAt}}
function eventPublic(e){return {...e,creatorName:db.users.find(u=>u.id===e.creatorId)?.name||'Unbekannt',className:e.classId?db.classes.find(c=>c.id===e.classId)?.name||'Unbekannt':null}}
function groupFilePublic(f){return {...f,ownerName:db.users.find(u=>u.id===f.ownerId)?.name||'Unbekannt'}}
function groupEventPublic(e){return {...e,creatorName:db.users.find(u=>u.id===e.creatorId)?.name||'Unbekannt'}}
function groupMember(u,gid){return db.groupMembers.some(m=>m.groupId===gid&&m.userId===u.id)}
function typingKey(type,id){return `${type}:${id}`}
function typingUsers(type,id,currentId){const key=typingKey(type,id),now=nowMs(),arr=typingState.get(key)||[];const live=arr.filter(x=>now-x.at<4000);typingState.set(key,live);return live.filter(x=>x.userId!==currentId).map(x=>{const u=db.users.find(y=>y.id===x.userId);return u?pub(u):null}).filter(Boolean)}
function storagePath(kind,id,stored){return `${kind}/${id}/${stored}`}
async function uploadToStorage(raw,storageKey,mimeType){const {error}=await supabase.storage.from(SUPABASE_BUCKET).upload(storageKey,raw,{contentType:mimeType||'application/octet-stream',upsert:false});if(error)throw error}
async function signedDownload(storageKey){const {data,error}=await supabase.storage.from(SUPABASE_BUCKET).createSignedUrl(storageKey,60);if(error)throw error;return data.signedUrl}
async function deleteStorage(storageKey){if(storageKey)await supabase.storage.from(SUPABASE_BUCKET).remove([storageKey])}
async function api(req,res,p){
 if(req.method==='GET'&&p==='/api/health')return send(res,200,{ok:true,app:'KlassenCloud',version:'V11',storage:'supabase'});

 if(req.method==='POST'&&p==='/api/register'){const b=await parse(req),name=String(b.name||'').trim(),pw=String(b.password||'');if(name.length<2||name.length>40||pw.length<8)return send(res,400,{error:'Name (2–40 Zeichen) und Passwort (mind. 8 Zeichen) erforderlich.'});if(!/^[\p{L}\p{N} ._'-]+$/u.test(name))return send(res,400,{error:'Der Name enthält ungültige Zeichen.'});if(db.users.some(u=>u.name.toLowerCase()===name.toLowerCase()))return send(res,400,{error:'Dieser Name ist bereits vergeben.'});const h=hash(pw),u={id:Date.now(),name,passwordHash:h.hash,passwordSalt:h.salt,role:'user',status:'active',createdAt:new Date().toISOString()};db.users.push(u);const className=String(b.className||'8A').trim();const cls=db.classes.find(c=>c.name.toLowerCase()===className.toLowerCase());if(!cls)return send(res,400,{error:'Diese Klasse gibt es nicht. Bitte wähle eine vorhandene Klasse.'});db.memberships.push({userId:u.id,classId:cls.id,role:'member'});save();return loginResponse(res,u)}
 if(req.method==='POST'&&p==='/api/login'){const b=await parse(req),name=String(b.name||'').trim(),u=db.users.find(x=>x.name.toLowerCase()===name.toLowerCase());if(!u||u.status!=='active')return send(res,401,{error:'Name oder Passwort falsch.'});const got=hash(String(b.password||''),u.passwordSalt).hash;if(!crypto.timingSafeEqual(Buffer.from(got,'hex'),Buffer.from(u.passwordHash,'hex')))return send(res,401,{error:'Name oder Passwort falsch.'});return loginResponse(res,u)}
 if(req.method==='POST'&&p==='/api/logout'){const c=cookies(req);if(c.sid){sessions.delete(c.sid);db.sessions=db.sessions.filter(x=>x.sid!==c.sid);save()}return send(res,200,{ok:true},{'Set-Cookie':'sid=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0'})}
 if(req.method==='GET'&&p==='/api/me'){const u=auth(req,res);if(!u)return;return send(res,200,{user:pub(u)})}
 if(req.method==='POST'&&p==='/api/presence'){const u=auth(req,res);if(!u)return;u.lastSeen=nowMs();save();return send(res,200,{online:true})}
 const tm=p.match(/^\/api\/typing\/(class|private|group)\/(\d+)$/);if(tm){const u=auth(req,res);if(!u)return;const type=tm[1],id=Number(tm[2]);if(type==='class'&&!member(u.id,id)&&u.role!=='admin')return send(res,403,{error:'Kein Zugriff.'});if(type==='group'&&!groupMember(u,id)&&u.role!=='admin')return send(res,403,{error:'Kein Zugriff.'});if(type==='private'){const other=db.users.find(x=>x.id===id);if(!privateAllowed(u,other))return send(res,403,{error:'Kein Zugriff.'})}const key=typingKey(type,id);if(req.method==='POST'){const b=await parse(req),on=!!b.typing;let arr=(typingState.get(key)||[]).filter(x=>x.userId!==u.id);if(on)arr.push({userId:u.id,at:nowMs()});typingState.set(key,arr);return send(res,200,{ok:true})}return send(res,200,{users:typingUsers(type,id,u.id)})}

 if(req.method==='GET'&&p==='/api/classes'){const u=auth(req,res);if(!u)return;const own=db.memberships.filter(m=>m.userId===u.id).map(m=>db.classes.find(c=>c.id===m.classId)).filter(Boolean);return send(res,200,{classes:own})}
 if(req.method==='GET'&&p==='/api/chat/overview'){const u=auth(req,res);if(!u)return;const classes=db.classes.filter(c=>member(u.id,c.id)||u.role==='admin').map(c=>({id:c.id,name:c.name,memberCount:db.memberships.filter(m=>m.classId===c.id).length}));const privateChats=db.chats.filter(c=>c.type==='private'&&(c.userA===u.id||c.userB===u.id)).map(c=>{const otherId=c.userA===u.id?c.userB:c.userA;const other=db.users.find(x=>x.id===otherId);return {id:c.id,other:other&&pub(other)}}).filter(x=>x.other);return send(res,200,{classes,privateChats})}
 const cm=p.match(/^\/api\/chat\/class\/(\d+)$/);if(cm){const u=auth(req,res);if(!u)return;const cid=Number(cm[1]);if(!db.classes.some(c=>c.id===cid))return send(res,404,{error:'Klasse nicht gefunden'});if(!member(u.id,cid)&&u.role!=='admin')return send(res,403,{error:'Du bist nicht Mitglied dieses Klassenchats.'});if(req.method==='GET'){const messages=db.messages.filter(m=>m.chatType==='class'&&m.chatId===cid).slice(-300).map(messagePublic);return send(res,200,{class:db.classes.find(c=>c.id===cid),messages,typing:typingUsers('class',cid,u.id)})}if(req.method==='POST'){const b=await parse(req),text=String(b.text||'').trim();if(!text||text.length>2000)return send(res,400,{error:'Nachricht ungültig.'});db.messages.push({id:Date.now()+Math.random(),chatType:'class',chatId:cid,userId:u.id,text,createdAt:new Date().toISOString()});save();return send(res,200,{ok:true})}}
 const pm=p.match(/^\/api\/chat\/private\/(\d+)$/);if(pm){const u=auth(req,res);if(!u)return;const otherId=Number(pm[1]),other=db.users.find(x=>x.id===otherId);if(!privateAllowed(u,other))return send(res,404,{error:'Dieser Benutzer ist nicht verfügbar.'});const c=chatForUsers(u.id,other.id);if(req.method==='GET'){return send(res,200,{chat:{id:c.id,other:pub(other)},messages:db.messages.filter(m=>m.chatType==='private'&&m.chatId===c.id).slice(-300).map(messagePublic),typing:typingUsers('private',other.id,u.id)})}if(req.method==='POST'){const b=await parse(req),text=String(b.text||'').trim();if(!text||text.length>2000)return send(res,400,{error:'Nachricht ungültig.'});db.messages.push({id:Date.now()+Math.random(),chatType:'private',chatId:c.id,userId:u.id,text,createdAt:new Date().toISOString()});save();return send(res,200,{ok:true})}}
 if(req.method==='GET'&&p==='/api/chat/users'){const u=auth(req,res);if(!u)return;const users=db.users.filter(x=>x.id!==u.id&&x.status==='active').map(pub);return send(res,200,{users})}
  const searchPath=p.match(/^\/api\/chat\/search\/(class|private|group)\/(\d+)$/);if(searchPath&&req.method==='GET'){const u=auth(req,res);if(!u)return;const type=searchPath[1],id=Number(searchPath[2]),q=(new URL(req.url,'http://localhost')).searchParams.get('q')?.trim().toLowerCase()||'';if(q.length<2)return send(res,200,{messages:[]});let msgs=[];if(type==='class'){if(!member(u.id,id)&&u.role!=='admin')return send(res,403,{error:'Kein Zugriff.'});msgs=db.messages.filter(m=>m.chatType==='class'&&m.chatId===id)}else if(type==='group'){if(!groupMember(u,id)&&u.role!=='admin')return send(res,403,{error:'Kein Zugriff.'});msgs=db.messages.filter(m=>m.chatType==='group'&&m.chatId===id)}else{const other=db.users.find(x=>x.id===id);if(!privateAllowed(u,other))return send(res,403,{error:'Kein Zugriff.'});const c=chatForUsers(u.id,other.id);msgs=db.messages.filter(m=>m.chatType==='private'&&m.chatId===c.id)}return send(res,200,{messages:msgs.filter(m=>m.text.toLowerCase().includes(q)).slice(-100).map(messagePublic)})}
 // GROUP CHATS: private groups with owner/member permissions
 if(req.method==='GET'&&p==='/api/groups'){const u=auth(req,res);if(!u)return;const groups=db.groups.filter(g=>u.role==='admin'||db.groupMembers.some(m=>m.groupId===g.id&&m.userId===u.id)).map(g=>({...g,ownerName:db.users.find(x=>x.id===g.ownerId)?.name||'Unbekannt',memberCount:db.groupMembers.filter(m=>m.groupId===g.id).length,members:db.groupMembers.filter(m=>m.groupId===g.id).map(m=>{const x=db.users.find(u=>u.id===m.userId);return x?{...pub(x),groupRole:m.role}:null}).filter(Boolean)}));return send(res,200,{groups})}
 if(req.method==='POST'&&p==='/api/groups'){const u=auth(req,res);if(!u)return;const b=await parse(req),name=String(b.name||'').trim();if(name.length<2||name.length>60)return send(res,400,{error:'Gruppenname muss 2–60 Zeichen lang sein.'});const g={id:Date.now(),name,ownerId:u.id,createdAt:new Date().toISOString()};db.groups.push(g);db.groupMembers.push({groupId:g.id,userId:u.id,role:'owner'});const ids=Array.isArray(b.memberIds)?b.memberIds.map(Number).filter(x=>x&&x!==u.id):[];for(const id of [...new Set(ids)])if(db.users.some(x=>x.id===id&&x.status==='active'))db.groupMembers.push({groupId:g.id,userId:id,role:'member'});save();return send(res,200,{group:{...g,ownerName:u.name}})}
 const gm=p.match(/^\/api\/groups\/(\d+)$/);if(gm){const u=auth(req,res);if(!u)return;const gid=Number(gm[1]),g=db.groups.find(x=>x.id===gid),membership=db.groupMembers.find(m=>m.groupId===gid&&m.userId===u.id);if(!g)return send(res,404,{error:'Gruppe nicht gefunden.'});if(!membership&&u.role!=='admin')return send(res,403,{error:'Du bist kein Mitglied dieser Gruppe.'});if(req.method==='GET'){const members=db.groupMembers.filter(m=>m.groupId===gid).map(m=>{const x=db.users.find(u=>u.id===m.userId);return x?{...pub(x),groupRole:m.role}:null}).filter(Boolean);const messages=db.messages.filter(m=>m.chatType==='group'&&m.chatId===gid).slice(-500).map(messagePublic);const files=db.groupFiles.filter(f=>f.groupId===gid).map(groupFilePublic);const events=db.groupEvents.filter(e=>e.groupId===gid).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)).map(groupEventPublic);return send(res,200,{group:{...g,closed:!!g.closed,ownerName:db.users.find(x=>x.id===g.ownerId)?.name||'Unbekannt'},members,messages,files,events,typing:typingUsers('group',gid,u.id)})}if(req.method==='POST'){if(g.closed&&g.ownerId!==u.id&&u.role!=='admin')return send(res,403,{error:'Diese Gruppe ist geschlossen.'});const b=await parse(req),text=String(b.text||'').trim();if(!text||text.length>2000)return send(res,400,{error:'Nachricht ungültig.'});db.messages.push({id:Date.now()+Math.random(),chatType:'group',chatId:gid,userId:u.id,text,createdAt:new Date().toISOString()});save();return send(res,200,{ok:true})}if(req.method==='DELETE'){if(g.ownerId!==u.id&&u.role!=='admin')return send(res,403,{error:'Nur Gruppenbesitzer oder Admin darf die Gruppe löschen.'});db.messages=db.messages.filter(m=>!(m.chatType==='group'&&m.chatId===gid));db.groupMembers=db.groupMembers.filter(m=>m.groupId!==gid);for(const f of db.groupFiles.filter(f=>f.groupId===gid)) await deleteStorage(f.storageKey||f.stored);db.groupFiles=db.groupFiles.filter(f=>f.groupId!==gid);db.groupEvents=db.groupEvents.filter(e=>e.groupId!==gid);db.groups=db.groups.filter(x=>x.id!==gid);save();return send(res,200,{ok:true})}}
 const gs=p.match(/^\/api\/groups\/(\d+)\/status$/);if(gs&&req.method==='PATCH'){const u=auth(req,res);if(!u)return;const gid=Number(gs[1]),g=db.groups.find(x=>x.id===gid);if(!g)return send(res,404,{error:'Gruppe nicht gefunden.'});if(g.ownerId!==u.id&&u.role!=='admin')return send(res,403,{error:'Nur Besitzer oder Admin darf die Gruppe schließen.'});const b=await parse(req);g.closed=!!b.closed;save();return send(res,200,{ok:true,closed:g.closed})}
 const gf=p.match(/^\/api\/groups\/(\d+)\/files$/);if(gf){const u=auth(req,res);if(!u)return;const gid=Number(gf[1]),g=db.groups.find(x=>x.id===gid);if(!g||(!groupMember(u,gid)&&u.role!=='admin'))return send(res,403,{error:'Kein Zugriff.'});if(req.method==='GET')return send(res,200,{files:db.groupFiles.filter(f=>f.groupId===gid).map(groupFilePublic)});if(req.method==='POST'){const b=await parse(req),name=String(b.name||'').trim(),data=String(b.data||'');if(!name||!data.includes(','))return send(res,400,{error:'Datei fehlt.'});const raw=Buffer.from(data.split(',')[1],'base64');if(raw.length>8*1024*1024)return send(res,400,{error:'Maximal 8 MB.'});const ext=path.extname(name).slice(0,12).replace(/[^a-zA-Z0-9.]/g,'');const stored=crypto.randomBytes(16).toString('hex')+ext;const storageKey=storagePath('groups',gid,stored);await uploadToStorage(raw,storageKey,String(b.mime||'application/octet-stream').slice(0,100));const f={id:Date.now()+Math.random(),groupId:gid,name:name.replace(/[\\/]/g,'_'),size:raw.length,mime:String(b.mime||'application/octet-stream').slice(0,100),ownerId:u.id,stored,storageKey,createdAt:new Date().toISOString()};db.groupFiles.push(f);save();return send(res,200,{file:groupFilePublic(f)})}}
 const gev=p.match(/^\/api\/groups\/(\d+)\/events(?:\/(\d+))?$/);if(gev){const u=auth(req,res);if(!u)return;const gid=Number(gev[1]),eid=gev[2]?Number(gev[2]):null,g=db.groups.find(x=>x.id===gid);if(!g||(!groupMember(u,gid)&&u.role!=='admin'))return send(res,403,{error:'Kein Zugriff.'});if(req.method==='GET')return send(res,200,{events:db.groupEvents.filter(e=>e.groupId===gid).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)).map(groupEventPublic)});if(req.method==='POST'){const b=await parse(req),title=String(b.title||'').trim(),date=String(b.date||''),time=String(b.time||'');if(!title||!/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/.test(date)||!/^[0-9]{2}:[0-9]{2}$/.test(time))return send(res,400,{error:'Titel, Datum und Uhrzeit erforderlich.'});const e={id:Date.now()+Math.random(),groupId:gid,title,date,time,description:String(b.description||'').slice(0,1000),creatorId:u.id,createdAt:new Date().toISOString()};db.groupEvents.push(e);save();return send(res,200,{event:groupEventPublic(e)})}if(req.method==='DELETE'&&eid){const e=db.groupEvents.find(x=>x.id===eid&&x.groupId===gid);if(!e)return send(res,404,{error:'Termin nicht gefunden.'});if(e.creatorId!==u.id&&g.ownerId!==u.id&&u.role!=='admin')return send(res,403,{error:'Keine Berechtigung.'});db.groupEvents=db.groupEvents.filter(x=>x.id!==eid);save();return send(res,200,{ok:true})}}
 const gfd=p.match(/^\/api\/groups\/(\d+)\/files\/(\d+)\/download$/);if(gfd&&req.method==='GET'){const u=auth(req,res);if(!u)return;const gid=Number(gfd[1]),fid=Number(gfd[2]),f=db.groupFiles.find(x=>x.id===fid&&x.groupId===gid);if(!f||(!groupMember(u,gid)&&u.role!=='admin'))return send(res,403,{error:'Keine Berechtigung.'});try{return send(res,200,{url:await signedDownload(f.storageKey||f.stored)})}catch(e){return send(res,404,{error:'Datei fehlt in Supabase Storage.'})}}
 const gmp=p.match(/^\/api\/groups\/(\d+)\/members\/(\d+)$/);if(gmp){const u=auth(req,res);if(!u)return;const gid=Number(gmp[1]),uid=Number(gmp[2]),g=db.groups.find(x=>x.id===gid),own=g&&g.ownerId===u.id;if(!g)return send(res,404,{error:'Gruppe nicht gefunden.'});if(!own&&u.role!=='admin')return send(res,403,{error:'Nur Gruppenbesitzer oder Admin darf Mitglieder verwalten.'});if(!db.users.some(x=>x.id===uid&&x.status==='active'))return send(res,404,{error:'Benutzer nicht gefunden.'});if(req.method==='POST'){if(!db.groupMembers.some(m=>m.groupId===gid&&m.userId===uid))db.groupMembers.push({groupId:gid,userId:uid,role:'member'});save();return send(res,200,{ok:true})}if(req.method==='DELETE'){if(uid===g.ownerId)return send(res,400,{error:'Der Besitzer kann nicht entfernt werden.'});db.groupMembers=db.groupMembers.filter(m=>!(m.groupId===gid&&m.userId===uid));save();return send(res,200,{ok:true})}}
 if(req.method==='GET'&&p==='/api/groups/users'){const u=auth(req,res);if(!u)return;return send(res,200,{users:db.users.filter(x=>x.id!==u.id&&x.status==='active').map(pub)})}
  const md=p.match(/^\/api\/messages\/(\d+)$/);if(md&&req.method==='DELETE'){const u=auth(req,res);if(!u)return;const m=db.messages.find(x=>x.id===Number(md[1]));if(!m)return send(res,404,{error:'Nachricht nicht gefunden.'});const allowed=m.userId===u.id||u.role==='admin';if(!allowed)return send(res,403,{error:'Du darfst nur deine eigenen Nachrichten löschen.'});db.messages=db.messages.filter(x=>x.id!==m.id);save();return send(res,200,{ok:true})}
 // CLOUD: private files or files shared with an entire class
 if(req.method==='GET'&&p==='/api/cloud'){const u=auth(req,res);if(!u)return;const ownClassIds=db.memberships.filter(m=>m.userId===u.id).map(m=>m.classId);const files=db.files.filter(f=>f.ownerId===u.id||(f.scope==='class'&&ownClassIds.includes(f.classId))||(u.role==='admin'&&f.scope==='class')).map(filePublic).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));return send(res,200,{files,classes:db.classes.filter(c=>ownClassIds.includes(c.id))})}
 if(req.method==='POST'&&p==='/api/cloud'){const u=auth(req,res);if(!u)return;const b=await parse(req),name=String(b.name||'').trim(),scope=b.scope==='class'?'class':'private',classId=Number(b.classId||0),data=String(b.data||'');if(!name||name.length>160)return send(res,400,{error:'Dateiname ungültig.'});if(!data||!data.includes(','))return send(res,400,{error:'Dateiinhalt fehlt.'});const raw=Buffer.from(data.split(',')[1],'base64');if(raw.length>8*1024*1024)return send(res,400,{error:'Datei zu groß. Maximal 8 MB.'});if(scope==='class'&&!member(u.id,classId)&&u.role!=='admin')return send(res,403,{error:'Du bist nicht Mitglied dieser Klasse.'});const ext=path.extname(name).slice(0,12).replace(/[^a-zA-Z0-9.]/g,'');const id=Date.now()+Math.random();const stored=crypto.randomBytes(16).toString('hex')+ext;const storageKey=storagePath(scope==='class'?'classes':'private',scope==='class'?classId:u.id,stored);await uploadToStorage(raw,storageKey,String(b.mime||'application/octet-stream').slice(0,100));const f={id,name:name.replace(/[\\/]/g,'_'),size:raw.length,mime:String(b.mime||'application/octet-stream').slice(0,100),scope,classId:scope==='class'?classId:null,ownerId:u.id,stored,storageKey,createdAt:new Date().toISOString()};db.files.push(f);save();return send(res,200,{file:filePublic(f)})}
 const fd=p.match(/^\/api\/cloud\/(\d+)\/download$/);if(fd&&req.method==='GET'){const u=auth(req,res);if(!u)return;const f=db.files.find(x=>x.id===Number(fd[1]));if(!f)return send(res,404,{error:'Datei nicht gefunden'});const allowed=f.ownerId===u.id||(f.scope==='class'&&member(u.id,f.classId))||(u.role==='admin'&&f.scope==='class');if(!allowed)return send(res,403,{error:'Keine Berechtigung für diese Datei.'});try{return send(res,200,{url:await signedDownload(f.storageKey||f.stored)})}catch(e){return send(res,404,{error:'Datei fehlt in Supabase Storage.'})}}
 const fx=p.match(/^\/api\/cloud\/(\d+)$/);if(fx&&req.method==='DELETE'){const u=auth(req,res);if(!u)return;const f=db.files.find(x=>x.id===Number(fx[1]));if(!f)return send(res,404,{error:'Datei nicht gefunden'});if(f.ownerId!==u.id&&u.role!=='admin')return send(res,403,{error:'Nur Besitzer oder Admin darf löschen.'});await deleteStorage(f.storageKey||f.stored);db.files=db.files.filter(x=>x.id!==f.id);save();return send(res,200,{ok:true})}
 // CLASS-WIDE CALENDAR: Homework, appointments, exams
 if(req.method==='GET'&&p==='/api/calendar'){const u=auth(req,res);if(!u)return;const classIds=db.memberships.filter(m=>m.userId===u.id).map(m=>m.classId);const classes=db.classes.filter(c=>classIds.includes(c.id));const events=db.events.filter(e=>classIds.includes(e.classId)).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)).map(eventPublic);return send(res,200,{events,classes})}
 if(req.method==='POST'&&p==='/api/calendar'){const u=auth(req,res);if(!u)return;const b=await parse(req),classId=Number(b.classId),type=['homework','appointment','exam'].includes(b.type)?b.type:'appointment',title=String(b.title||'').trim(),date=String(b.date||''),time=String(b.time||'');if(!member(u.id,classId)&&u.role!=='admin')return send(res,403,{error:'Du bist nicht Mitglied dieser Klasse.'});if(!title||!/^\d{4}-\d{2}-\d{2}$/.test(date)||!/^\d{2}:\d{2}$/.test(time))return send(res,400,{error:'Titel, Datum und Uhrzeit sind erforderlich.'});const e={id:Date.now()+Math.random(),classId,type,title,date,time,description:String(b.description||'').slice(0,1000),subject:String(b.subject||'').slice(0,80),createdBy:u.id,creatorId:u.id,createdAt:new Date().toISOString()};db.events.push(e);save();return send(res,200,{event:eventPublic(e)})}
 const ed=p.match(/^\/api\/calendar\/(\d+)$/);if(ed&&req.method==='DELETE'){const u=auth(req,res);if(!u)return;const e=db.events.find(x=>x.id===Number(ed[1]));if(!e)return send(res,404,{error:'Termin nicht gefunden'});if(e.creatorId!==u.id&&u.role!=='admin')return send(res,403,{error:'Nur Ersteller oder Admin darf löschen.'});db.events=db.events.filter(x=>x.id!==e.id);save();return send(res,200,{ok:true})}
  if(req.method==='GET'&&p==='/api/timetable'){const u=auth(req,res);if(!u)return;const ids=db.memberships.filter(m=>m.userId===u.id).map(m=>m.classId);const classes=db.classes.filter(c=>ids.includes(c.id));return send(res,200,{classes,settings:db.timetableSettings,timetable:db.timetable.filter(t=>ids.includes(t.classId)||u.role==='admin').sort((a,b)=>(a.day-b.day)||(a.period-b.period))})}
 if(req.method==='POST'&&p==='/api/admin/timetable'){const a=admin(req,res);if(!a)return;const b=await parse(req),classId=Number(b.classId),day=Number(b.day),period=Number(b.period),subject=String(b.subject||'').trim(),teacher=String(b.teacher||'').trim(),room=String(b.room||'').trim();if(!db.classes.some(c=>c.id===classId)||day<1||day>5||period<1||!subject)return send(res,400,{error:'Klasse, Tag, Stunde und Fach sind erforderlich.'});const existing=db.timetable.find(t=>t.classId===classId&&t.day===day&&t.period===period);if(existing)Object.assign(existing,{subject,teacher,room});else db.timetable.push({id:Date.now()+Math.random(),classId,day,period,subject,teacher,room});save();return send(res,200,{ok:true})}
 if(req.method==='POST'&&p==='/api/admin/timetable/settings'){const a=admin(req,res);if(!a)return;const b=await parse(req),classId=Number(b.classId),lessonMinutes=Math.max(1,Math.min(180,Number(b.lessonMinutes)||45)),breakMinutes=Math.max(0,Math.min(120,Number(b.breakMinutes)||15));let st=db.timetableSettings.find(x=>x.classId===classId);if(!st){st={classId,lessonMinutes,breakMinutes};db.timetableSettings.push(st)}else Object.assign(st,{lessonMinutes,breakMinutes});save();return send(res,200,{ok:true})}
if(req.method==='GET'&&p==='/api/admin/users'){const a=admin(req,res);if(!a)return;return send(res,200,{users:db.users.map(pub)})}
 if(req.method==='GET'&&p==='/api/admin/stats'){const a=admin(req,res);if(!a)return;return send(res,200,{users:db.users.length,active:db.users.filter(x=>x.status==='active').length,banned:db.users.filter(x=>x.status==='banned').length,admins:db.users.filter(x=>x.role==='admin').length,classes:db.classes.length,classMembers:db.memberships.length,messages:db.messages.length,groups:db.groups.length,groupMembers:db.groupMembers.length,files:db.files.length,events:db.events.length})}
 if(req.method==='GET'&&p==='/api/admin/audit'){const a=admin(req,res);if(!a)return;return send(res,200,{logs:db.audit.map(x=>({...x,adminName:db.users.find(u=>u.id===x.adminId)?.name||'Unbekannt'}))})}
 if(req.method==='GET'&&p==='/api/admin/classes'){const a=admin(req,res);if(!a)return;return send(res,200,{classes:db.classes.map(c=>({...c,members:db.memberships.filter(m=>m.classId===c.id).map(m=>{const u=db.users.find(x=>x.id===m.userId);return u?pub(u):null}).filter(Boolean)}))})}
 const ac=p.match(/^\/api\/admin\/classes\/(\d+)\/members\/(\d+)$/);if(ac){const a=admin(req,res);if(!a)return;const cid=Number(ac[1]),uid=Number(ac[2]);if(!db.classes.some(c=>c.id===cid)||!db.users.some(u=>u.id===uid))return send(res,404,{error:'Nicht gefunden'});if(req.method==='POST'){if(!member(uid,cid)){db.memberships.push({userId:uid,classId:cid,role:'member'});audit(a.id,'CLASS_ADD_MEMBER',`User ${uid} -> Klasse ${cid}`);save()}return send(res,200,{ok:true})}if(req.method==='DELETE'){db.memberships=db.memberships.filter(m=>!(m.userId===uid&&m.classId===cid));audit(a.id,'CLASS_REMOVE_MEMBER',`User ${uid} aus Klasse ${cid}`);save();return send(res,200,{ok:true})}}
 if(req.method==='POST'&&p==='/api/admin/classes'){const a=admin(req,res),b=await parse(req);if(!a)return;if(!String(b.name||'').trim())return send(res,400,{error:'Klassenname fehlt.'});const name=String(b.name).trim();if(db.classes.some(c=>c.name.toLowerCase()===name.toLowerCase()))return send(res,400,{error:'Klasse existiert bereits.'});const c={id:Date.now(),name,ownerId:a.id,createdAt:new Date().toISOString()};db.classes.push(c);db.memberships.push({userId:a.id,classId:c.id,role:'admin'});audit(a.id,'CLASS_CREATE',name);save();return send(res,200,{class:c})}
 const au=p.match(/^\/api\/admin\/users\/(\d+)$/);if(au){const a=admin(req,res);if(!a)return;const id=Number(au[1]),u=db.users.find(x=>x.id===id);if(!u)return send(res,404,{error:'Benutzer nicht gefunden'});if(req.method==='PATCH'){const b=await parse(req);if(id===a.id&&b.status==='banned')return send(res,400,{error:'Du kannst dich nicht selbst sperren.'});if(b.role&&['user','admin'].includes(b.role))u.role=b.role;if(b.status&&['active','banned'].includes(b.status))u.status=b.status;audit(a.id,'USER_UPDATE',`User ${id}`);save();return send(res,200,{ok:true})}if(req.method==='DELETE'){if(id===a.id)return send(res,400,{error:'Du kannst dich nicht selbst löschen.'});db.users=db.users.filter(x=>x.id!==id);db.memberships=db.memberships.filter(m=>m.userId!==id);db.chats=db.chats.filter(c=>c.userA!==id&&c.userB!==id);db.groupMembers=db.groupMembers.filter(m=>m.userId!==id);db.groups=db.groups.filter(g=>g.ownerId!==id);for(const f of db.groupFiles.filter(f=>f.ownerId===id)) await deleteStorage(f.storageKey||f.stored);db.groupFiles=db.groupFiles.filter(f=>f.ownerId!==id);db.groupEvents=db.groupEvents.filter(e=>e.creatorId!==id);db.messages=db.messages.filter(m=>m.userId!==id);for(const f of db.files.filter(f=>f.ownerId===id)) await deleteStorage(f.storageKey||f.stored);db.files=db.files.filter(f=>f.ownerId!==id);db.events=db.events.filter(e=>e.creatorId!==id);audit(a.id,'USER_DELETE',`User ${id}`);save();return send(res,200,{ok:true})}}
 send(res,404,{error:'Nicht gefunden'})
}
function loginResponse(res,u){u.lastSeen=Date.now();const sid=crypto.randomBytes(32).toString('hex');sessions.set(sid,u.id);db.sessions=db.sessions.filter(x=>x.userId!==u.id||x.expiresAt<=Date.now());db.sessions.push({sid,userId:u.id,expiresAt:Date.now()+604800000,createdAt:new Date().toISOString()});save();return send(res,200,{ok:true,user:pub(u)},{'Set-Cookie':`sid=${sid}; HttpOnly; SameSite=Lax; Path=/; Max-Age=604800`})}
const server=http.createServer(async(req,res)=>{try{const p=url.parse(req.url).pathname;if(p.startsWith('/api/'))return await api(req,res,p);let file=path.normalize(path.join(ROOT,p==='/'?'index.html':p));if(!file.startsWith(ROOT))return send(res,403,'Forbidden');if(!fs.existsSync(file)||fs.statSync(file).isDirectory())file=path.join(ROOT,'index.html');res.writeHead(200,{'Content-Type':mime[path.extname(file)]||'application/octet-stream'});fs.createReadStream(file).pipe(res)}catch(e){console.error(e);send(res,500,{error:'Serverfehler'})}});
const port=Number(process.env.PORT||3000);server.on('error',e=>{console.error(e);process.exit(1)});(async()=>{try{await loadDB();let changed=seed();changed=seedTimetable()||changed;if(changed)await persist();await ensureBucket();server.listen(port,'0.0.0.0',()=>console.log(`KlassenCloud läuft auf Port ${port}`))}catch(e){console.error('Start fehlgeschlagen:',e);process.exit(1)}})();
